use crate::models::*;

pub const OFFICIAL_CHINESE_CVV_CS: &str = include_str!("../../official_openutau_sources/ChineseCVVPhonemizer.cs");
pub const OFFICIAL_KOREAN_CVC_CS: &str = include_str!("../../official_openutau_sources/KoreanCVCPhonemizer.cs");
pub const OFFICIAL_CANTONESE_CVVC_CS: &str = include_str!("../../official_openutau_sources/CantoneseCVVCPhonemizer.cs");

pub fn create_korean_hangul_preset() -> PhonemizerProject {
    PhonemizerProject {
        name: "KoreanCVCPhonemizer".to_string(),
        tag: "KO CVC".to_string(),
        author: "NANA".to_string(),
        version: "1.0.0".to_string(),
        language_code: "KO".to_string(),
        description: "Official OpenUtau Korean CVC Phonemizer with Unicode Hangul decomposition (choseong, jungseong, jongseong / batchim) and romanization".to_string(),
        namespace: "OpenUtau.Plugin.Builtin".to_string(),
        base_class_type: PhonemeSystemType::CustomDirect,
        openutau_plugins_dir: default_openutau_plugins_path(),
        output_dll_name: "KoreanCVCPhonemizer.dll".to_string(),
        vowels: vec![
            Vowel::new("a"),
            Vowel::new("eo"),
            Vowel::new("o"),
            Vowel::new("u"),
            Vowel::new("eu"),
            Vowel::new("i"),
            Vowel::new("e"),
            Vowel::new("ya"),
            Vowel::new("yeo"),
            Vowel::new("yo"),
            Vowel::new("yu"),
            Vowel::new("ye"),
            Vowel::new("wa"),
            Vowel::new("weo"),
            Vowel::new("wi"),
            Vowel::new("we"),
            Vowel::new("eui"),
        ],
        consonants: vec![
            Consonant::new("g", ConsonantType::Stop),
            Consonant::new("gg", ConsonantType::Stop),
            Consonant::new("n", ConsonantType::Nasal),
            Consonant::new("d", ConsonantType::Stop),
            Consonant::new("dd", ConsonantType::Stop),
            Consonant::new("r", ConsonantType::Liquid),
            Consonant::new("l", ConsonantType::Liquid),
            Consonant::new("m", ConsonantType::Nasal),
            Consonant::new("b", ConsonantType::Stop),
            Consonant::new("bb", ConsonantType::Stop),
            Consonant::new("s", ConsonantType::Fricative),
            Consonant::new("ss", ConsonantType::Fricative),
            Consonant::new("j", ConsonantType::Affricate),
            Consonant::new("jj", ConsonantType::Affricate),
            Consonant::new("ch", ConsonantType::Affricate),
            Consonant::new("k", ConsonantType::Stop),
            Consonant::new("t", ConsonantType::Stop),
            Consonant::new("p", ConsonantType::Stop),
            Consonant::new("h", ConsonantType::Fricative),
            Consonant::new("ng", ConsonantType::Nasal),
        ],
        onset_clusters: vec![],
        coda_clusters: vec![],
        pattern_rules: vec![
            PhoneticPatternRule { pattern_type: PatternType::RestingStartVowel, template: "- {vowel}".to_string(), enabled: true, priority: 10, fallback_template: Some("{vowel}".to_string()), min_pitch_note: None, max_pitch_note: None, color_filter: None },
            PhoneticPatternRule { pattern_type: PatternType::RestingStartConsonant, template: "- {consonant}{vowel}".to_string(), enabled: true, priority: 10, fallback_template: Some("{consonant}{vowel}".to_string()), min_pitch_note: None, max_pitch_note: None, color_filter: None },
            PhoneticPatternRule { pattern_type: PatternType::VCV, template: "{prev_vowel} {consonant}{vowel}".to_string(), enabled: true, priority: 9, fallback_template: Some("{consonant}{vowel}".to_string()), min_pitch_note: None, max_pitch_note: None, color_filter: None },
            PhoneticPatternRule { pattern_type: PatternType::CV, template: "{consonant}{vowel}".to_string(), enabled: true, priority: 8, fallback_template: None, min_pitch_note: None, max_pitch_note: None, color_filter: None },
            PhoneticPatternRule { pattern_type: PatternType::VC, template: "{prev_vowel} {consonant}".to_string(), enabled: true, priority: 7, fallback_template: None, min_pitch_note: None, max_pitch_note: None, color_filter: None },
            PhoneticPatternRule { pattern_type: PatternType::EndingVowelGlide, template: "{vowel} -".to_string(), enabled: true, priority: 5, fallback_template: None, min_pitch_note: None, max_pitch_note: None, color_filter: None },
        ],
        voice_color_and_pitch: VoiceColorAndPitchConfig::default(),
        syllabification_config: SyllabificationConfig::default(),
        dictionary_overrides: vec![],
        regex_rules: vec![],
        allow_fallback_cv: true,
        allow_fallback_vv: true,
        split_ratio_onset: 0.5,
        split_ratio_coda: 0.5,
        max_consonant_duration_ms: 120,
        raw_csharp_source: Some(OFFICIAL_KOREAN_CVC_CS.to_string()),
        source_github_url: Some("https://raw.githubusercontent.com/openutau/OpenUtau/master/OpenUtau.Plugin.Builtin/KoreanCVCPhonemizer.cs".to_string()),
        custom_usings: vec![
            "using System;".to_string(),
            "using System.Collections.Generic;".to_string(),
            "using System.Linq;".to_string(),
            "using OpenUtau.Api;".to_string(),
            "using OpenUtau.Core;".to_string(),
            "using OpenUtau.Core.Ustx;".to_string(),
        ],
        custom_class_fields: String::new(),
        custom_preprocess_code: String::new(),
        custom_postprocess_code: String::new(),
        custom_helper_methods: String::new(),
            test_cases: Vec::new(),
    }
}

pub fn create_chinese_cvv_preset() -> PhonemizerProject {
    PhonemizerProject {
        name: "ChineseCVVMonophonePhonemizer".to_string(),
        tag: "ZH CVV".to_string(),
        author: "stakira".to_string(),
        version: "1.0.0".to_string(),
        language_code: "ZH".to_string(),
        description: "Official OpenUtau Chinese CVV Phonemizer with automatic Pinyin decomposition and tail splitting (_ang, _eng, _ong, etc.)".to_string(),
        namespace: "OpenUtau.Plugin.Builtin".to_string(),
        base_class_type: PhonemeSystemType::CustomDirect,
        openutau_plugins_dir: default_openutau_plugins_path(),
        output_dll_name: "ChineseCVVPhonemizer.dll".to_string(),
        vowels: vec![
            Vowel::new("a"),
            Vowel::new("o"),
            Vowel::new("e"),
            Vowel::new("i"),
            Vowel::new("u"),
            Vowel::new("v"),
            Vowel::new("ai"),
            Vowel::new("ei"),
            Vowel::new("ui"),
            Vowel::new("ao"),
            Vowel::new("ou"),
            Vowel::new("iu"),
            Vowel::new("ie"),
            Vowel::new("ve"),
            Vowel::new("er"),
            Vowel::new("an"),
            Vowel::new("en"),
            Vowel::new("in"),
            Vowel::new("un"),
            Vowel::new("vn"),
            Vowel::new("ang"),
            Vowel::new("eng"),
            Vowel::new("ing"),
            Vowel::new("ong"),
        ],
        consonants: vec![
            Consonant::new("b", ConsonantType::Stop),
            Consonant::new("p", ConsonantType::Stop),
            Consonant::new("m", ConsonantType::Nasal),
            Consonant::new("f", ConsonantType::Fricative),
            Consonant::new("d", ConsonantType::Stop),
            Consonant::new("t", ConsonantType::Stop),
            Consonant::new("n", ConsonantType::Nasal),
            Consonant::new("l", ConsonantType::Liquid),
            Consonant::new("g", ConsonantType::Stop),
            Consonant::new("k", ConsonantType::Stop),
            Consonant::new("h", ConsonantType::Fricative),
            Consonant::new("j", ConsonantType::Affricate),
            Consonant::new("q", ConsonantType::Affricate),
            Consonant::new("x", ConsonantType::Fricative),
            Consonant::new("zh", ConsonantType::Affricate),
            Consonant::new("ch", ConsonantType::Affricate),
            Consonant::new("sh", ConsonantType::Fricative),
            Consonant::new("r", ConsonantType::Liquid),
            Consonant::new("z", ConsonantType::Affricate),
            Consonant::new("c", ConsonantType::Affricate),
            Consonant::new("s", ConsonantType::Fricative),
            Consonant::new("y", ConsonantType::Semivowel),
            Consonant::new("w", ConsonantType::Semivowel),
        ],
        onset_clusters: vec![],
        coda_clusters: vec![],
        pattern_rules: vec![
            PhoneticPatternRule { pattern_type: PatternType::RestingStartVowel, template: "{pinyin}".to_string(), enabled: true, priority: 10, fallback_template: None, min_pitch_note: None, max_pitch_note: None, color_filter: None },
            PhoneticPatternRule { pattern_type: PatternType::CV, template: "{pinyin}".to_string(), enabled: true, priority: 9, fallback_template: None, min_pitch_note: None, max_pitch_note: None, color_filter: None },
            PhoneticPatternRule { pattern_type: PatternType::EndingVowelGlide, template: "_{tail}".to_string(), enabled: true, priority: 8, fallback_template: None, min_pitch_note: None, max_pitch_note: None, color_filter: None },
        ],
        voice_color_and_pitch: VoiceColorAndPitchConfig::default(),
        syllabification_config: SyllabificationConfig::default(),
        dictionary_overrides: vec![],
        regex_rules: vec![],
        allow_fallback_cv: true,
        allow_fallback_vv: true,
        split_ratio_onset: 0.5,
        split_ratio_coda: 0.5,
        max_consonant_duration_ms: 120,
        raw_csharp_source: Some(OFFICIAL_CHINESE_CVV_CS.to_string()),
        source_github_url: Some("https://raw.githubusercontent.com/openutau/OpenUtau/master/OpenUtau.Plugin.Builtin/ChineseCVVPhonemizer.cs".to_string()),
        custom_usings: vec![
            "using System;".to_string(),
            "using System.Collections.Generic;".to_string(),
            "using System.Linq;".to_string(),
            "using OpenUtau.Api;".to_string(),
            "using OpenUtau.Core;".to_string(),
            "using OpenUtau.Core.Ustx;".to_string(),
        ],
        custom_class_fields: String::new(),
        custom_preprocess_code: String::new(),
        custom_postprocess_code: String::new(),
        custom_helper_methods: String::new(),
            test_cases: Vec::new(),
    }
}

pub fn create_cantonese_preset() -> PhonemizerProject {
    PhonemizerProject {
        name: "CantoneseCVVCPhonemizer".to_string(),
        tag: "YUE CVVC".to_string(),
        author: "stakira".to_string(),
        version: "1.0.0".to_string(),
        language_code: "YUE".to_string(),
        description: "Official OpenUtau Cantonese (Yue) CVVC Phonemizer with Jyutping support.".to_string(),
        namespace: "OpenUtau.Plugin.Builtin".to_string(),
        base_class_type: PhonemeSystemType::CustomDirect,
        openutau_plugins_dir: default_openutau_plugins_path(),
        output_dll_name: "CantoneseCVVCPhonemizer.dll".to_string(),
        vowels: vec![
            Vowel::new("aa"),
            Vowel::new("a"),
            Vowel::new("e"),
            Vowel::new("i"),
            Vowel::new("o"),
            Vowel::new("u"),
            Vowel::new("oe"),
            Vowel::new("eo"),
            Vowel::new("yu"),
        ],
        consonants: vec![
            Consonant::new("b", ConsonantType::Stop),
            Consonant::new("p", ConsonantType::Stop),
            Consonant::new("m", ConsonantType::Nasal),
            Consonant::new("f", ConsonantType::Fricative),
            Consonant::new("d", ConsonantType::Stop),
            Consonant::new("t", ConsonantType::Stop),
            Consonant::new("n", ConsonantType::Nasal),
            Consonant::new("l", ConsonantType::Liquid),
            Consonant::new("g", ConsonantType::Stop),
            Consonant::new("k", ConsonantType::Stop),
            Consonant::new("ng", ConsonantType::Nasal),
            Consonant::new("h", ConsonantType::Fricative),
            Consonant::new("gw", ConsonantType::Stop),
            Consonant::new("kw", ConsonantType::Stop),
            Consonant::new("w", ConsonantType::Semivowel),
            Consonant::new("z", ConsonantType::Affricate),
            Consonant::new("c", ConsonantType::Affricate),
            Consonant::new("s", ConsonantType::Fricative),
            Consonant::new("j", ConsonantType::Semivowel),
        ],
        onset_clusters: vec![],
        coda_clusters: vec![],
        pattern_rules: vec![],
        voice_color_and_pitch: VoiceColorAndPitchConfig::default(),
        syllabification_config: SyllabificationConfig::default(),
        dictionary_overrides: vec![],
        regex_rules: vec![],
        allow_fallback_cv: true,
        allow_fallback_vv: true,
        split_ratio_onset: 0.5,
        split_ratio_coda: 0.5,
        max_consonant_duration_ms: 120,
        raw_csharp_source: Some(OFFICIAL_CANTONESE_CVVC_CS.to_string()),
        source_github_url: Some("https://raw.githubusercontent.com/openutau/OpenUtau/master/OpenUtau.Plugin.Builtin/CantoneseCVVCPhonemizer.cs".to_string()),
        custom_usings: vec![
            "using System;".to_string(),
            "using System.Collections.Generic;".to_string(),
            "using System.Linq;".to_string(),
            "using OpenUtau.Api;".to_string(),
        ],
        custom_class_fields: String::new(),
        custom_preprocess_code: String::new(),
        custom_postprocess_code: String::new(),
        custom_helper_methods: String::new(),
            test_cases: Vec::new(),
    }
}
