use crate::models::*;

pub const OFFICIAL_ARPASING_CS: &str = include_str!("../../official_openutau_sources/ArpasingPhonemizer.cs");
pub const OFFICIAL_ENGLISH_VCCV_CS: &str = include_str!("../../official_openutau_sources/EnglishVCCVPhonemizer.cs");

pub fn create_english_arpasing_preset() -> PhonemizerProject {
    PhonemizerProject {
        name: "ArpasingPhonemizer".to_string(),
        tag: "EN ARPA".to_string(),
        author: "stakira".to_string(),
        version: "1.0.0".to_string(),
        language_code: "EN".to_string(),
        description: "Official OpenUtau English Arpasing Phonemizer. CMUdict diphone-based English phonemizer with automatic vowel fallbacks.".to_string(),
        namespace: "OpenUtau.Plugin.Builtin".to_string(),
        base_class_type: PhonemeSystemType::Arpasing,
        openutau_plugins_dir: default_openutau_plugins_path(),
        output_dll_name: "ArpasingPhonemizer.dll".to_string(),
        vowels: vec![
            Vowel { symbol: "aa".to_string(), ipa: "ɑ".to_string(), aliases: vec![], is_nasal: false, is_diphthong: false, is_triphthong: false, second_vowel: None, third_vowel: None, diphthong_split_ratio: 0.5, end_glide: Some("aa -".to_string()), glottal_start_alias: None, elongation_symbol: None, stress_variants: vec![], color_overrides: vec![] },
            Vowel { symbol: "ae".to_string(), ipa: "æ".to_string(), aliases: vec![], is_nasal: false, is_diphthong: false, is_triphthong: false, second_vowel: None, third_vowel: None, diphthong_split_ratio: 0.5, end_glide: Some("ae -".to_string()), glottal_start_alias: None, elongation_symbol: None, stress_variants: vec![], color_overrides: vec![] },
            Vowel { symbol: "ah".to_string(), ipa: "ʌ".to_string(), aliases: vec![], is_nasal: false, is_diphthong: false, is_triphthong: false, second_vowel: None, third_vowel: None, diphthong_split_ratio: 0.5, end_glide: Some("ah -".to_string()), glottal_start_alias: None, elongation_symbol: None, stress_variants: vec![], color_overrides: vec![] },
            Vowel { symbol: "ao".to_string(), ipa: "ɔ".to_string(), aliases: vec![], is_nasal: false, is_diphthong: false, is_triphthong: false, second_vowel: None, third_vowel: None, diphthong_split_ratio: 0.5, end_glide: Some("ao -".to_string()), glottal_start_alias: None, elongation_symbol: None, stress_variants: vec![], color_overrides: vec![] },
            Vowel { symbol: "aw".to_string(), ipa: "aʊ".to_string(), aliases: vec![], is_nasal: false, is_diphthong: true, is_triphthong: false, second_vowel: Some("uh".to_string()), third_vowel: None, diphthong_split_ratio: 0.6, end_glide: Some("aw -".to_string()), glottal_start_alias: None, elongation_symbol: None, stress_variants: vec![], color_overrides: vec![] },
            Vowel { symbol: "ay".to_string(), ipa: "aɪ".to_string(), aliases: vec![], is_nasal: false, is_diphthong: true, is_triphthong: false, second_vowel: Some("ih".to_string()), third_vowel: None, diphthong_split_ratio: 0.6, end_glide: Some("ay -".to_string()), glottal_start_alias: None, elongation_symbol: None, stress_variants: vec![], color_overrides: vec![] },
            Vowel { symbol: "eh".to_string(), ipa: "ɛ".to_string(), aliases: vec![], is_nasal: false, is_diphthong: false, is_triphthong: false, second_vowel: None, third_vowel: None, diphthong_split_ratio: 0.5, end_glide: Some("eh -".to_string()), glottal_start_alias: None, elongation_symbol: None, stress_variants: vec![], color_overrides: vec![] },
            Vowel { symbol: "er".to_string(), ipa: "ɝ".to_string(), aliases: vec![], is_nasal: false, is_diphthong: false, is_triphthong: false, second_vowel: None, third_vowel: None, diphthong_split_ratio: 0.5, end_glide: Some("er -".to_string()), glottal_start_alias: None, elongation_symbol: None, stress_variants: vec![], color_overrides: vec![] },
            Vowel { symbol: "ey".to_string(), ipa: "eɪ".to_string(), aliases: vec![], is_nasal: false, is_diphthong: true, is_triphthong: false, second_vowel: Some("ih".to_string()), third_vowel: None, diphthong_split_ratio: 0.6, end_glide: Some("ey -".to_string()), glottal_start_alias: None, elongation_symbol: None, stress_variants: vec![], color_overrides: vec![] },
            Vowel { symbol: "ih".to_string(), ipa: "ɪ".to_string(), aliases: vec![], is_nasal: false, is_diphthong: false, is_triphthong: false, second_vowel: None, third_vowel: None, diphthong_split_ratio: 0.5, end_glide: Some("ih -".to_string()), glottal_start_alias: None, elongation_symbol: None, stress_variants: vec![], color_overrides: vec![] },
            Vowel { symbol: "iy".to_string(), ipa: "i".to_string(), aliases: vec![], is_nasal: false, is_diphthong: false, is_triphthong: false, second_vowel: None, third_vowel: None, diphthong_split_ratio: 0.5, end_glide: Some("iy -".to_string()), glottal_start_alias: None, elongation_symbol: None, stress_variants: vec![], color_overrides: vec![] },
            Vowel { symbol: "ow".to_string(), ipa: "oʊ".to_string(), aliases: vec![], is_nasal: false, is_diphthong: true, is_triphthong: false, second_vowel: Some("uh".to_string()), third_vowel: None, diphthong_split_ratio: 0.6, end_glide: Some("ow -".to_string()), glottal_start_alias: None, elongation_symbol: None, stress_variants: vec![], color_overrides: vec![] },
            Vowel { symbol: "oy".to_string(), ipa: "ɔɪ".to_string(), aliases: vec![], is_nasal: false, is_diphthong: true, is_triphthong: false, second_vowel: Some("ih".to_string()), third_vowel: None, diphthong_split_ratio: 0.6, end_glide: Some("oy -".to_string()), glottal_start_alias: None, elongation_symbol: None, stress_variants: vec![], color_overrides: vec![] },
            Vowel { symbol: "uh".to_string(), ipa: "ʊ".to_string(), aliases: vec![], is_nasal: false, is_diphthong: false, is_triphthong: false, second_vowel: None, third_vowel: None, diphthong_split_ratio: 0.5, end_glide: Some("uh -".to_string()), glottal_start_alias: None, elongation_symbol: None, stress_variants: vec![], color_overrides: vec![] },
            Vowel { symbol: "uw".to_string(), ipa: "u".to_string(), aliases: vec![], is_nasal: false, is_diphthong: false, is_triphthong: false, second_vowel: None, third_vowel: None, diphthong_split_ratio: 0.5, end_glide: Some("uw -".to_string()), glottal_start_alias: None, elongation_symbol: None, stress_variants: vec![], color_overrides: vec![] },
        ],
        consonants: vec![
            Consonant::new("b", ConsonantType::Stop),
            Consonant::new("ch", ConsonantType::Affricate),
            Consonant::new("d", ConsonantType::Stop),
            Consonant::new("dh", ConsonantType::Fricative),
            Consonant::new("f", ConsonantType::Fricative),
            Consonant::new("g", ConsonantType::Stop),
            Consonant::new("hh", ConsonantType::Fricative),
            Consonant::new("jh", ConsonantType::Affricate),
            Consonant::new("k", ConsonantType::Stop),
            Consonant::new("l", ConsonantType::Liquid),
            Consonant::new("m", ConsonantType::Nasal),
            Consonant::new("n", ConsonantType::Nasal),
            Consonant::new("ng", ConsonantType::Nasal),
            Consonant::new("p", ConsonantType::Stop),
            Consonant::new("r", ConsonantType::Liquid),
            Consonant::new("s", ConsonantType::Fricative),
            Consonant::new("sh", ConsonantType::Fricative),
            Consonant::new("t", ConsonantType::Stop),
            Consonant::new("th", ConsonantType::Fricative),
            Consonant::new("v", ConsonantType::Fricative),
            Consonant::new("w", ConsonantType::Semivowel),
            Consonant::new("y", ConsonantType::Semivowel),
            Consonant::new("z", ConsonantType::Fricative),
            Consonant::new("zh", ConsonantType::Fricative),
        ],
        onset_clusters: vec![],
        coda_clusters: vec![],
        pattern_rules: vec![
            PhoneticPatternRule { pattern_type: PatternType::RestingStartVowel, template: "- {vowel}".to_string(), enabled: true, priority: 10, fallback_template: Some("{vowel}".to_string()), min_pitch_note: None, max_pitch_note: None, color_filter: None },
            PhoneticPatternRule { pattern_type: PatternType::RestingStartConsonant, template: "- {consonant}".to_string(), enabled: true, priority: 10, fallback_template: Some("{consonant}".to_string()), min_pitch_note: None, max_pitch_note: None, color_filter: None },
            PhoneticPatternRule { pattern_type: PatternType::CV, template: "{consonant} {vowel}".to_string(), enabled: true, priority: 9, fallback_template: None, min_pitch_note: None, max_pitch_note: None, color_filter: None },
            PhoneticPatternRule { pattern_type: PatternType::VC, template: "{prev_vowel} {consonant}".to_string(), enabled: true, priority: 8, fallback_template: None, min_pitch_note: None, max_pitch_note: None, color_filter: None },
            PhoneticPatternRule { pattern_type: PatternType::VV, template: "{prev_vowel} {vowel}".to_string(), enabled: true, priority: 7, fallback_template: None, min_pitch_note: None, max_pitch_note: None, color_filter: None },
            PhoneticPatternRule { pattern_type: PatternType::CC, template: "{prev_consonant} {consonant}".to_string(), enabled: true, priority: 6, fallback_template: None, min_pitch_note: None, max_pitch_note: None, color_filter: None },
            PhoneticPatternRule { pattern_type: PatternType::EndingVowelGlide, template: "{vowel} -".to_string(), enabled: true, priority: 5, fallback_template: None, min_pitch_note: None, max_pitch_note: None, color_filter: None },
            PhoneticPatternRule { pattern_type: PatternType::EndingConsonantCoda, template: "{consonant} -".to_string(), enabled: true, priority: 5, fallback_template: None, min_pitch_note: None, max_pitch_note: None, color_filter: None },
        ],
        voice_color_and_pitch: VoiceColorAndPitchConfig::default(),
        syllabification_config: SyllabificationConfig::default(),
        dictionary_overrides: vec![],
        regex_rules: vec![],
        allow_fallback_cv: true,
        allow_fallback_vv: true,
        split_ratio_onset: 0.5,
        split_ratio_coda: 0.5,
        max_consonant_duration_ms: 120,
        raw_csharp_source: Some(OFFICIAL_ARPASING_CS.to_string()),
        source_github_url: Some("https://raw.githubusercontent.com/openutau/OpenUtau/master/OpenUtau.Plugin.Builtin/ArpasingPhonemizer.cs".to_string()),
        custom_usings: vec![
            "using System;".to_string(),
            "using System.Collections.Generic;".to_string(),
            "using System.Linq;".to_string(),
            "using OpenUtau.Api;".to_string(),
            "using OpenUtau.Core.G2p;".to_string(),
        ],
        custom_class_fields: String::new(),
        custom_preprocess_code: String::new(),
        custom_postprocess_code: String::new(),
        custom_helper_methods: String::new(),
            test_cases: Vec::new(),
    }
}

pub fn create_english_vccv_preset() -> PhonemizerProject {
    PhonemizerProject {
        name: "EnglishVCCVPhonemizer".to_string(),
        tag: "EN VCCV".to_string(),
        author: "cubialpha & Mim".to_string(),
        version: "1.0.0".to_string(),
        language_code: "EN".to_string(),
        description: "Official OpenUtau English VCCV Phonemizer with Cz VCCV voicebank rules and convel support.".to_string(),
        namespace: "OpenUtau.Plugin.Builtin".to_string(),
        base_class_type: PhonemeSystemType::SyllableBased,
        openutau_plugins_dir: default_openutau_plugins_path(),
        output_dll_name: "EnglishVCCVPhonemizer.dll".to_string(),
        vowels: vec![
            Vowel::new("a"),
            Vowel::new("@"),
            Vowel::new("u"),
            Vowel::new("0"),
            Vowel::new("8"),
            Vowel::new("I"),
            Vowel::new("e"),
            Vowel::new("3"),
            Vowel::new("A"),
            Vowel::new("i"),
            Vowel::new("E"),
            Vowel::new("O"),
            Vowel::new("Q"),
            Vowel::new("6"),
            Vowel::new("o"),
            Vowel::new("1ng"),
            Vowel::new("9"),
            Vowel::new("&"),
            Vowel::new("x"),
            Vowel::new("1"),
            Vowel::new("Y"),
            Vowel::new("L"),
            Vowel::new("W"),
            Vowel::new("8n"),
            Vowel::new("Ang"),
            Vowel::new("9l"),
        ],
        consonants: vec![
            Consonant::new("b", ConsonantType::Stop),
            Consonant::new("ch", ConsonantType::Affricate),
            Consonant::new("d", ConsonantType::Stop),
            Consonant::new("dh", ConsonantType::Fricative),
            Consonant::new("f", ConsonantType::Fricative),
            Consonant::new("g", ConsonantType::Stop),
            Consonant::new("h", ConsonantType::Fricative),
            Consonant::new("j", ConsonantType::Affricate),
            Consonant::new("k", ConsonantType::Stop),
            Consonant::new("l", ConsonantType::Liquid),
            Consonant::new("m", ConsonantType::Nasal),
            Consonant::new("n", ConsonantType::Nasal),
            Consonant::new("ng", ConsonantType::Nasal),
            Consonant::new("p", ConsonantType::Stop),
            Consonant::new("r", ConsonantType::Liquid),
            Consonant::new("s", ConsonantType::Fricative),
            Consonant::new("sh", ConsonantType::Fricative),
            Consonant::new("t", ConsonantType::Stop),
            Consonant::new("th", ConsonantType::Fricative),
            Consonant::new("v", ConsonantType::Fricative),
            Consonant::new("w", ConsonantType::Semivowel),
            Consonant::new("y", ConsonantType::Semivowel),
            Consonant::new("z", ConsonantType::Fricative),
            Consonant::new("zh", ConsonantType::Fricative),
            Consonant::new("dd", ConsonantType::Stop),
            Consonant::new("hh", ConsonantType::Fricative),
            Consonant::new("sp", ConsonantType::Stop),
            Consonant::new("st", ConsonantType::Stop),
        ],
        onset_clusters: vec![],
        coda_clusters: vec![],
        pattern_rules: vec![],
        voice_color_and_pitch: VoiceColorAndPitchConfig::default(),
        syllabification_config: SyllabificationConfig::default(),
        dictionary_overrides: vec![],
        regex_rules: vec![],
        allow_fallback_cv: true,
        allow_fallback_vv: true,
        split_ratio_onset: 0.5,
        split_ratio_coda: 0.5,
        max_consonant_duration_ms: 120,
        raw_csharp_source: Some(OFFICIAL_ENGLISH_VCCV_CS.to_string()),
        source_github_url: Some("https://raw.githubusercontent.com/openutau/OpenUtau/master/OpenUtau.Plugin.Builtin/EnglishVCCVPhonemizer.cs".to_string()),
        custom_usings: vec![
            "using System;".to_string(),
            "using System.Collections.Generic;".to_string(),
            "using System.Linq;".to_string(),
            "using OpenUtau.Api;".to_string(),
            "using OpenUtau.Core.G2p;".to_string(),
        ],
        custom_class_fields: String::new(),
        custom_preprocess_code: String::new(),
        custom_postprocess_code: String::new(),
        custom_helper_methods: String::new(),
            test_cases: Vec::new(),
    }
}
