use crate::models::*;

pub const OFFICIAL_FRENCH_CVVC_CS: &str = include_str!("../../official_openutau_sources/FrenchCVVCPhonemizer.cs");

pub fn create_french_preset() -> PhonemizerProject {
    PhonemizerProject {
        name: "FrenchCVVCPhonemizer".to_string(),
        tag: "FR CVVC".to_string(),
        author: "Mim".to_string(),
        version: "1.0.0".to_string(),
        language_code: "FR".to_string(),
        description: "Official OpenUtau French CVVC Phonemizer by Mim with Fraloids fallback, liaison rules, nasal vowels, and glide transitions.".to_string(),
        namespace: "OpenUtau.Plugin.Builtin".to_string(),
        base_class_type: PhonemeSystemType::SyllableBased,
        openutau_plugins_dir: default_openutau_plugins_path(),
        output_dll_name: "FrenchCVVCPhonemizer.dll".to_string(),
        vowels: vec![
            Vowel::new("ah"),
            Vowel::new("ae"),
            Vowel::new("eh"),
            Vowel::new("ee"),
            Vowel::new("oe"),
            Vowel::new("ih"),
            Vowel::new("oh"),
            Vowel::new("oo"),
            Vowel::new("ou"),
            Vowel::new("uh"),
            Vowel::new("en"),
            Vowel::new("in"),
            Vowel::new("on"),
            Vowel::new("oi"),
            Vowel::new("ui"),
            Vowel::new("a"),
            Vowel::new("ai"),
            Vowel::new("e"),
            Vowel::new("i"),
            Vowel::new("o"),
            Vowel::new("u"),
            Vowel::new("eu"),
        ],
        consonants: vec![
            Consonant::new("b", ConsonantType::Stop),
            Consonant::new("d", ConsonantType::Stop),
            Consonant::new("f", ConsonantType::Fricative),
            Consonant::new("g", ConsonantType::Stop),
            Consonant::new("j", ConsonantType::Fricative),
            Consonant::new("k", ConsonantType::Stop),
            Consonant::new("l", ConsonantType::Liquid),
            Consonant::new("m", ConsonantType::Nasal),
            Consonant::new("n", ConsonantType::Nasal),
            Consonant::new("p", ConsonantType::Stop),
            Consonant::new("r", ConsonantType::Liquid),
            Consonant::new("s", ConsonantType::Fricative),
            Consonant::new("sh", ConsonantType::Fricative),
            Consonant::new("t", ConsonantType::Stop),
            Consonant::new("v", ConsonantType::Fricative),
            Consonant::new("w", ConsonantType::Semivowel),
            Consonant::new("y", ConsonantType::Semivowel),
            Consonant::new("z", ConsonantType::Fricative),
            Consonant::new("gn", ConsonantType::Nasal),
        ],
        onset_clusters: vec![],
        coda_clusters: vec![],
        pattern_rules: vec![],
        voice_color_and_pitch: VoiceColorAndPitchConfig::default(),
        syllabification_config: SyllabificationConfig::default(),
        dictionary_overrides: vec![],
        regex_rules: vec![
            RegexRule::new("G2P aa -> ah", "aa", "ah", 1),
            RegexRule::new("G2P ai -> ae", "ai", "ae", 2),
            RegexRule::new("G2P ei -> eh", "ei", "eh", 3),
            RegexRule::new("G2P an -> en", "an", "en", 4),
            RegexRule::new("G2P un -> in", "un", "in", 5),
            RegexRule::new("G2P ch -> sh", "ch", "sh", 6),
        ],
        allow_fallback_cv: true,
        allow_fallback_vv: true,
        split_ratio_onset: 0.5,
        split_ratio_coda: 0.5,
        max_consonant_duration_ms: 120,
        raw_csharp_source: Some(OFFICIAL_FRENCH_CVVC_CS.to_string()),
        source_github_url: Some("https://raw.githubusercontent.com/openutau/OpenUtau/master/OpenUtau.Plugin.Builtin/FrenchCVVCPhonemizer.cs".to_string()),
        custom_usings: vec![
            "using System;".to_string(),
            "using System.Collections.Generic;".to_string(),
            "using System.Linq;".to_string(),
            "using OpenUtau.Api;".to_string(),
        ],
        custom_class_fields: String::new(),
        custom_preprocess_code: String::new(),
        custom_postprocess_code: String::new(),
        custom_helper_methods: String::new(),
            test_cases: Vec::new(),
    }
}
