use crate::models::*;

pub const OFFICIAL_GERMAN_VCCV_CS: &str = include_str!("../../official_openutau_sources/GermanVCCVPhonemizer.cs");

pub fn create_german_vccv_preset() -> PhonemizerProject {
    PhonemizerProject {
        name: "GermanVCCVPhonemizer".to_string(),
        tag: "DE VCCV".to_string(),
        author: "Lotte V".to_string(),
        version: "1.0.0".to_string(),
        language_code: "DE".to_string(),
        description: "Official OpenUtau German VCCV Phonemizer by Lotte V based on Felix's VCCV voicebank.".to_string(),
        namespace: "OpenUtau.Plugin.Builtin".to_string(),
        base_class_type: PhonemeSystemType::SyllableBased,
        openutau_plugins_dir: default_openutau_plugins_path(),
        output_dll_name: "GermanVCCVPhonemizer.dll".to_string(),
        vowels: vec![
            Vowel::new("a"),
            Vowel::new("6"),
            Vowel::new("e"),
            Vowel::new("E"),
            Vowel::new("2"),
            Vowel::new("9"),
            Vowel::new("i"),
            Vowel::new("I"),
            Vowel::new("y"),
            Vowel::new("Y"),
            Vowel::new("u"),
            Vowel::new("U"),
            Vowel::new("o"),
            Vowel::new("O"),
            Vowel::new("@"),
            Vowel::new("aU"),
            Vowel::new("OY"),
            Vowel::new("aI"),
        ],
        consonants: vec![
            Consonant::new("-", ConsonantType::Stop),
            Consonant::new("b", ConsonantType::Stop),
            Consonant::new("C", ConsonantType::Fricative),
            Consonant::new("d", ConsonantType::Stop),
            Consonant::new("f", ConsonantType::Fricative),
            Consonant::new("g", ConsonantType::Stop),
            Consonant::new("h", ConsonantType::Fricative),
            Consonant::new("j", ConsonantType::Semivowel),
            Consonant::new("k", ConsonantType::Stop),
            Consonant::new("kh", ConsonantType::Stop),
            Consonant::new("l", ConsonantType::Liquid),
            Consonant::new("m", ConsonantType::Nasal),
            Consonant::new("n", ConsonantType::Nasal),
            Consonant::new("N", ConsonantType::Nasal),
            Consonant::new("p", ConsonantType::Stop),
            Consonant::new("ph", ConsonantType::Stop),
            Consonant::new("R;", ConsonantType::Liquid),
            Consonant::new("s", ConsonantType::Fricative),
            Consonant::new("S", ConsonantType::Fricative),
            Consonant::new("t", ConsonantType::Stop),
            Consonant::new("th", ConsonantType::Stop),
            Consonant::new("v", ConsonantType::Fricative),
            Consonant::new("x", ConsonantType::Fricative),
            Consonant::new("z", ConsonantType::Fricative),
            Consonant::new("Z", ConsonantType::Fricative),
            Consonant::new("dZ", ConsonantType::Affricate),
            Consonant::new("ks", ConsonantType::Affricate),
            Consonant::new("pf", ConsonantType::Affricate),
            Consonant::new("st", ConsonantType::Stop),
            Consonant::new("St", ConsonantType::Stop),
            Consonant::new("tS", ConsonantType::Affricate),
            Consonant::new("w", ConsonantType::Semivowel),
        ],
        onset_clusters: vec![],
        coda_clusters: vec![],
        pattern_rules: vec![],
        voice_color_and_pitch: VoiceColorAndPitchConfig::default(),
        syllabification_config: SyllabificationConfig::default(),
        dictionary_overrides: vec![],
        regex_rules: vec![
            RegexRule::new("G2P aa -> a", "aa", "a", 1),
            RegexRule::new("G2P ae -> E", "ae", "E", 2),
            RegexRule::new("G2P ah -> @", "ah", "@", 3),
            RegexRule::new("G2P ao -> O", "ao", "O", 4),
            RegexRule::new("G2P aw -> aU", "aw", "aU", 5),
            RegexRule::new("G2P ay -> aI", "ay", "aI", 6),
            RegexRule::new("G2P cc -> C", "cc", "C", 7),
            RegexRule::new("G2P ch -> tS", "ch", "tS", 8),
            RegexRule::new("G2P sh -> S", "sh", "S", 9),
        ],
        allow_fallback_cv: true,
        allow_fallback_vv: true,
        split_ratio_onset: 0.5,
        split_ratio_coda: 0.5,
        max_consonant_duration_ms: 120,
        raw_csharp_source: Some(OFFICIAL_GERMAN_VCCV_CS.to_string()),
        source_github_url: Some("https://raw.githubusercontent.com/openutau/OpenUtau/master/OpenUtau.Plugin.Builtin/GermanVCCVPhonemizer.cs".to_string()),
        custom_usings: vec![
            "using System;".to_string(),
            "using System.Collections.Generic;".to_string(),
            "using System.Linq;".to_string(),
            "using OpenUtau.Api;".to_string(),
            "using OpenUtau.Core.G2p;".to_string(),
        ],
        custom_class_fields: String::new(),
        custom_preprocess_code: String::new(),
        custom_postprocess_code: String::new(),
        custom_helper_methods: String::new(),
            test_cases: Vec::new(),
    }
}
