use crate::models::*;

pub const OFFICIAL_ITALIAN_SYLLABLE_CS: &str = include_str!("../../official_openutau_sources/ItalianSyllableBasedPhonemizer.cs");

pub fn create_italian_preset() -> PhonemizerProject {
    PhonemizerProject {
        name: "ItalianSyllableBasedPhonemizer".to_string(),
        tag: "IT SYL".to_string(),
        author: "Lotte V".to_string(),
        version: "1.0.0".to_string(),
        language_code: "IT".to_string(),
        description: "Official OpenUtau Italian Syllable-Based Phonemizer by Lotte V based on Makkusan's list and cmudict_it.".to_string(),
        namespace: "OpenUtau.Plugin.Builtin".to_string(),
        base_class_type: PhonemeSystemType::SyllableBased,
        openutau_plugins_dir: default_openutau_plugins_path(),
        output_dll_name: "ItalianSyllableBasedPhonemizer.dll".to_string(),
        vowels: vec![
            Vowel::new("a"),
            Vowel::new("e"),
            Vowel::new("i"),
            Vowel::new("o"),
            Vowel::new("u"),
            Vowel::new("3"),
            Vowel::new("0"),
        ],
        consonants: vec![
            Consonant::new("b", ConsonantType::Stop),
            Consonant::new("d", ConsonantType::Stop),
            Consonant::new("dz", ConsonantType::Affricate),
            Consonant::new("dZ", ConsonantType::Affricate),
            Consonant::new("f", ConsonantType::Fricative),
            Consonant::new("g", ConsonantType::Stop),
            Consonant::new("gn", ConsonantType::Nasal),
            Consonant::new("j", ConsonantType::Semivowel),
            Consonant::new("k", ConsonantType::Stop),
            Consonant::new("l", ConsonantType::Liquid),
            Consonant::new("m", ConsonantType::Nasal),
            Consonant::new("M", ConsonantType::Nasal),
            Consonant::new("n", ConsonantType::Nasal),
            Consonant::new("N", ConsonantType::Nasal),
            Consonant::new("p", ConsonantType::Stop),
            Consonant::new("r", ConsonantType::Liquid),
            Consonant::new("rr", ConsonantType::Liquid),
            Consonant::new("s", ConsonantType::Fricative),
            Consonant::new("S", ConsonantType::Fricative),
            Consonant::new("t", ConsonantType::Stop),
            Consonant::new("ts", ConsonantType::Affricate),
            Consonant::new("tS", ConsonantType::Affricate),
            Consonant::new("v", ConsonantType::Fricative),
            Consonant::new("w", ConsonantType::Semivowel),
            Consonant::new("y", ConsonantType::Semivowel),
            Consonant::new("z", ConsonantType::Fricative),
        ],
        onset_clusters: vec![],
        coda_clusters: vec![],
        pattern_rules: vec![],
        voice_color_and_pitch: VoiceColorAndPitchConfig::default(),
        syllabification_config: SyllabificationConfig::default(),
        dictionary_overrides: vec![],
        regex_rules: vec![
            RegexRule::new("G2P EE -> 3", "EE", "3", 1),
            RegexRule::new("G2P OO -> 0", "OO", "0", 2),
            RegexRule::new("G2P dZZ -> dZ", "dZZ", "dZ", 3),
            RegexRule::new("G2P JJ -> gn", "JJ", "gn", 4),
            RegexRule::new("G2P SS -> S", "SS", "S", 5),
            RegexRule::new("G2P tSS -> tS", "tSS", "tS", 6),
        ],
        allow_fallback_cv: true,
        allow_fallback_vv: true,
        split_ratio_onset: 0.5,
        split_ratio_coda: 0.5,
        max_consonant_duration_ms: 120,
        raw_csharp_source: Some(OFFICIAL_ITALIAN_SYLLABLE_CS.to_string()),
        source_github_url: Some("https://raw.githubusercontent.com/openutau/OpenUtau/master/OpenUtau.Plugin.Builtin/ItalianSyllableBasedPhonemizer.cs".to_string()),
        custom_usings: vec![
            "using System;".to_string(),
            "using System.Collections.Generic;".to_string(),
            "using System.Linq;".to_string(),
            "using OpenUtau.Api;".to_string(),
            "using OpenUtau.Core.G2p;".to_string(),
        ],
        custom_class_fields: String::new(),
        custom_preprocess_code: String::new(),
        custom_postprocess_code: String::new(),
        custom_helper_methods: String::new(),
            test_cases: Vec::new(),
    }
}
