use crate::models::*;

pub const OFFICIAL_JAPANESE_VCV_CS: &str = include_str!("../../official_openutau_sources/JapaneseVCVPhonemizer.cs");
pub const OFFICIAL_JAPANESE_CVVC_CS: &str = include_str!("../../official_openutau_sources/JapaneseCVVCPhonemizer.cs");
pub const OFFICIAL_JAPANESE_PRESAMP_CS: &str = include_str!("../../official_openutau_sources/JapanesePresampPhonemizer.cs");

pub fn create_japanese_vcv_preset() -> PhonemizerProject {
    PhonemizerProject {
        name: "JapaneseVCVPhonemizer".to_string(),
        tag: "JA VCV".to_string(),
        author: "stakira".to_string(),
        version: "1.0.0".to_string(),
        language_code: "JA".to_string(),
        description: "Official OpenUtau Japanese VCV Phonemizer with automatic tail vowel lookup (a, e, i, o, n, u, N) and phonetic hints".to_string(),
        namespace: "OpenUtau.Plugin.Builtin".to_string(),
        base_class_type: PhonemeSystemType::JapaneseVCV,
        openutau_plugins_dir: default_openutau_plugins_path(),
        output_dll_name: "JapaneseVCVPhonemizer.dll".to_string(),
        vowels: vec![
            Vowel {
                symbol: "a".to_string(),
                ipa: "a".to_string(),
                aliases: vec!["".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string()],
                is_nasal: false,
                is_diphthong: false,
                is_triphthong: false,
                second_vowel: None,
                third_vowel: None,
                diphthong_split_ratio: 0.5,
                end_glide: Some("a -".to_string()),
                glottal_start_alias: None,
                elongation_symbol: Some("".to_string()),
                stress_variants: vec![],
                color_overrides: vec![],
            },
            Vowel {
                symbol: "e".to_string(),
                ipa: "e".to_string(),
                aliases: vec!["".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string()],
                is_nasal: false,
                is_diphthong: false,
                is_triphthong: false,
                second_vowel: None,
                third_vowel: None,
                diphthong_split_ratio: 0.5,
                end_glide: Some("e -".to_string()),
                glottal_start_alias: None,
                elongation_symbol: Some("".to_string()),
                stress_variants: vec![],
                color_overrides: vec![],
            },
            Vowel {
                symbol: "i".to_string(),
                ipa: "i".to_string(),
                aliases: vec!["".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string()],
                is_nasal: false,
                is_diphthong: false,
                is_triphthong: false,
                second_vowel: None,
                third_vowel: None,
                diphthong_split_ratio: 0.5,
                end_glide: Some("i -".to_string()),
                glottal_start_alias: None,
                elongation_symbol: Some("".to_string()),
                stress_variants: vec![],
                color_overrides: vec![],
            },
            Vowel {
                symbol: "o".to_string(),
                ipa: "o".to_string(),
                aliases: vec!["".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string()],
                is_nasal: false,
                is_diphthong: false,
                is_triphthong: false,
                second_vowel: None,
                third_vowel: None,
                diphthong_split_ratio: 0.5,
                end_glide: Some("o -".to_string()),
                glottal_start_alias: None,
                elongation_symbol: Some("".to_string()),
                stress_variants: vec![],
                color_overrides: vec![],
            },
            Vowel {
                symbol: "u".to_string(),
                ipa: "ɯ".to_string(),
                aliases: vec!["".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string(), "".to_string()],
                is_nasal: false,
                is_diphthong: false,
                is_triphthong: false,
                second_vowel: None,
                third_vowel: None,
                diphthong_split_ratio: 0.5,
                end_glide: Some("u -".to_string()),
                glottal_start_alias: None,
                elongation_symbol: Some("".to_string()),
                stress_variants: vec![],
                color_overrides: vec![],
            },
            Vowel {
                symbol: "n".to_string(),
                ipa: "ɴ".to_string(),
                aliases: vec!["".to_string()],
                is_nasal: true,
                is_diphthong: false,
                is_triphthong: false,
                second_vowel: None,
                third_vowel: None,
                diphthong_split_ratio: 0.5,
                end_glide: Some("n -".to_string()),
                glottal_start_alias: None,
                elongation_symbol: None,
                stress_variants: vec![],
                color_overrides: vec![],
            },
            Vowel {
                symbol: "N".to_string(),
                ipa: "ŋ".to_string(),
                aliases: vec!["".to_string(), "ng".to_string()],
                is_nasal: true,
                is_diphthong: false,
                is_triphthong: false,
                second_vowel: None,
                third_vowel: None,
                diphthong_split_ratio: 0.5,
                end_glide: None,
                glottal_start_alias: None,
                elongation_symbol: None,
                stress_variants: vec![],
                color_overrides: vec![],
            },
        ],
        consonants: vec![
            Consonant::new("k", ConsonantType::Stop),
            Consonant::new("g", ConsonantType::Stop),
            Consonant::new("s", ConsonantType::Fricative),
            Consonant::new("z", ConsonantType::Fricative),
            Consonant::new("t", ConsonantType::Stop),
            Consonant::new("d", ConsonantType::Stop),
            Consonant::new("n", ConsonantType::Nasal),
            Consonant::new("h", ConsonantType::Fricative),
            Consonant::new("b", ConsonantType::Stop),
            Consonant::new("p", ConsonantType::Stop),
            Consonant::new("m", ConsonantType::Nasal),
            Consonant::new("y", ConsonantType::Semivowel),
            Consonant::new("r", ConsonantType::Liquid),
            Consonant::new("w", ConsonantType::Semivowel),
            Consonant::new("ky", ConsonantType::Stop),
            Consonant::new("gy", ConsonantType::Stop),
            Consonant::new("sh", ConsonantType::Fricative),
            Consonant::new("j", ConsonantType::Affricate),
            Consonant::new("ch", ConsonantType::Affricate),
            Consonant::new("ts", ConsonantType::Affricate),
            Consonant::new("ny", ConsonantType::Nasal),
            Consonant::new("hy", ConsonantType::Fricative),
            Consonant::new("by", ConsonantType::Stop),
            Consonant::new("py", ConsonantType::Stop),
            Consonant::new("my", ConsonantType::Nasal),
            Consonant::new("ry", ConsonantType::Liquid),
        ],
        onset_clusters: vec![],
        coda_clusters: vec![],
        pattern_rules: vec![
            PhoneticPatternRule { pattern_type: PatternType::RestingStartVowel, template: "- {lyric}".to_string(), enabled: true, priority: 10, fallback_template: Some("{lyric}".to_string()), min_pitch_note: None, max_pitch_note: None, color_filter: None },
            PhoneticPatternRule { pattern_type: PatternType::VCV, template: "{prev_vowel} {lyric}".to_string(), enabled: true, priority: 9, fallback_template: Some("* {lyric}".to_string()), min_pitch_note: None, max_pitch_note: None, color_filter: None },
            PhoneticPatternRule { pattern_type: PatternType::CV, template: "{lyric}".to_string(), enabled: true, priority: 8, fallback_template: None, min_pitch_note: None, max_pitch_note: None, color_filter: None },
        ],
        voice_color_and_pitch: VoiceColorAndPitchConfig::default(),
        syllabification_config: SyllabificationConfig::default(),
        dictionary_overrides: vec![],
        regex_rules: vec![],
        allow_fallback_cv: true,
        allow_fallback_vv: true,
        split_ratio_onset: 0.5,
        split_ratio_coda: 0.5,
        max_consonant_duration_ms: 120,
        raw_csharp_source: Some(OFFICIAL_JAPANESE_VCV_CS.to_string()),
        source_github_url: Some("https://raw.githubusercontent.com/openutau/OpenUtau/master/OpenUtau.Plugin.Builtin/JapaneseVCVPhonemizer.cs".to_string()),
        custom_usings: vec![
            "using System.Collections.Generic;".to_string(),
            "using System.Linq;".to_string(),
            "using OpenUtau.Api;".to_string(),
            "using OpenUtau.Core.Ustx;".to_string(),
        ],
        custom_class_fields: String::new(),
        custom_preprocess_code: String::new(),
        custom_postprocess_code: String::new(),
        custom_helper_methods: String::new(),
            test_cases: Vec::new(),
    }
}

pub fn create_japanese_cvvc_preset() -> PhonemizerProject {
    PhonemizerProject {
        name: "JapaneseCVVCPhonemizer".to_string(),
        tag: "JA CVVC".to_string(),
        author: "TUBS".to_string(),
        version: "1.0.0".to_string(),
        language_code: "JA".to_string(),
        description: "Official OpenUtau Japanese CVVC Phonemizer by TUBS with full hiragana/katakana delta transitions".to_string(),
        namespace: "OpenUtau.Plugin.Builtin".to_string(),
        base_class_type: PhonemeSystemType::JapaneseCVVC,
        openutau_plugins_dir: default_openutau_plugins_path(),
        output_dll_name: "JapaneseCVVCPhonemizer.dll".to_string(),
        vowels: vec![
            Vowel::new(""),
            Vowel::new(""),
            Vowel::new(""),
            Vowel::new(""),
            Vowel::new(""),
            Vowel::new(""),
            Vowel::new(""),
            Vowel::new(""),
        ],
        consonants: vec![
            Consonant::new("k", ConsonantType::Stop),
            Consonant::new("ky", ConsonantType::Stop),
            Consonant::new("g", ConsonantType::Stop),
            Consonant::new("gy", ConsonantType::Stop),
            Consonant::new("s", ConsonantType::Fricative),
            Consonant::new("sh", ConsonantType::Fricative),
            Consonant::new("z", ConsonantType::Fricative),
            Consonant::new("j", ConsonantType::Affricate),
            Consonant::new("t", ConsonantType::Stop),
            Consonant::new("ch", ConsonantType::Affricate),
            Consonant::new("ty", ConsonantType::Stop),
            Consonant::new("ts", ConsonantType::Affricate),
            Consonant::new("d", ConsonantType::Stop),
            Consonant::new("dy", ConsonantType::Stop),
            Consonant::new("n", ConsonantType::Nasal),
            Consonant::new("ny", ConsonantType::Nasal),
            Consonant::new("h", ConsonantType::Fricative),
            Consonant::new("hy", ConsonantType::Fricative),
            Consonant::new("f", ConsonantType::Fricative),
            Consonant::new("b", ConsonantType::Stop),
            Consonant::new("by", ConsonantType::Stop),
            Consonant::new("p", ConsonantType::Stop),
            Consonant::new("py", ConsonantType::Stop),
            Consonant::new("m", ConsonantType::Nasal),
            Consonant::new("my", ConsonantType::Nasal),
            Consonant::new("y", ConsonantType::Semivowel),
            Consonant::new("r", ConsonantType::Liquid),
            Consonant::new("ry", ConsonantType::Liquid),
            Consonant::new("w", ConsonantType::Semivowel),
            Consonant::new("v", ConsonantType::Fricative),
            Consonant::new("ng", ConsonantType::Nasal),
        ],
        onset_clusters: vec![],
        coda_clusters: vec![],
        pattern_rules: vec![],
        voice_color_and_pitch: VoiceColorAndPitchConfig::default(),
        syllabification_config: SyllabificationConfig::default(),
        dictionary_overrides: vec![],
        regex_rules: vec![],
        allow_fallback_cv: true,
        allow_fallback_vv: true,
        split_ratio_onset: 0.5,
        split_ratio_coda: 0.5,
        max_consonant_duration_ms: 120,
        raw_csharp_source: Some(OFFICIAL_JAPANESE_CVVC_CS.to_string()),
        source_github_url: Some("https://raw.githubusercontent.com/openutau/OpenUtau/master/OpenUtau.Plugin.Builtin/JapaneseCVVCPhonemizer.cs".to_string()),
        custom_usings: vec![
            "using System;".to_string(),
            "using System.Collections.Generic;".to_string(),
            "using System.Linq;".to_string(),
            "using OpenUtau.Api;".to_string(),
            "using OpenUtau.Core.Ustx;".to_string(),
        ],
        custom_class_fields: String::new(),
        custom_preprocess_code: String::new(),
        custom_postprocess_code: String::new(),
        custom_helper_methods: String::new(),
            test_cases: Vec::new(),
    }
}
