use crate::models::*;

pub const OFFICIAL_POLISH_CVC_CS: &str = include_str!("../../official_openutau_sources/PolishCVCPhonemizer.cs");
pub const OFFICIAL_THAI_VCCV_CS: &str = include_str!("../../official_openutau_sources/ThaiVCCVPhonemizer.cs");
pub const OFFICIAL_TURKISH_CVVC_CS: &str = include_str!("../../official_openutau_sources/TurkishCVVCPhonemizer.cs");
pub const OFFICIAL_VIETNAMESE_CVVC_CS: &str = include_str!("../../official_openutau_sources/VietnameseCVVCPhonemizer.cs");
pub const OFFICIAL_LATIN_DIPHONE_CS: &str = include_str!("../../official_openutau_sources/LatinDiphonePhonemizer.cs");

pub fn create_polish_preset() -> PhonemizerProject {
    PhonemizerProject {
        name: "PolishCVCPhonemizer".to_string(),
        tag: "PL CVC".to_string(),
        author: "Heiden.BZR".to_string(),
        version: "1.0.0".to_string(),
        language_code: "PL".to_string(),
        description: "Official OpenUtau Polish CVC Phonemizer by Heiden.BZR.".to_string(),
        namespace: "OpenUtau.Plugin.Builtin".to_string(),
        base_class_type: PhonemeSystemType::SyllableBased,
        openutau_plugins_dir: default_openutau_plugins_path(),
        output_dll_name: "PolishCVCPhonemizer.dll".to_string(),
        vowels: vec![
            Vowel::new("a"),
            Vowel::new("e"),
            Vowel::new("o"),
            Vowel::new("u"),
            Vowel::new("y"),
            Vowel::new("i"),
            Vowel::new("an"),
            Vowel::new("en"),
        ],
        consonants: vec![
            Consonant::new("b", ConsonantType::Stop),
            Consonant::new("d", ConsonantType::Stop),
            Consonant::new("f", ConsonantType::Fricative),
            Consonant::new("g", ConsonantType::Stop),
            Consonant::new("h", ConsonantType::Fricative),
            Consonant::new("j", ConsonantType::Semivowel),
            Consonant::new("k", ConsonantType::Stop),
            Consonant::new("l", ConsonantType::Liquid),
            Consonant::new("m", ConsonantType::Nasal),
            Consonant::new("n", ConsonantType::Nasal),
            Consonant::new("p", ConsonantType::Stop),
            Consonant::new("r", ConsonantType::Liquid),
            Consonant::new("s", ConsonantType::Fricative),
            Consonant::new("t", ConsonantType::Stop),
            Consonant::new("v", ConsonantType::Fricative),
            Consonant::new("w", ConsonantType::Semivowel),
            Consonant::new("z", ConsonantType::Fricative),
        ],
        onset_clusters: vec![],
        coda_clusters: vec![],
        pattern_rules: vec![],
        voice_color_and_pitch: VoiceColorAndPitchConfig::default(),
        syllabification_config: SyllabificationConfig::default(),
        dictionary_overrides: vec![],
        regex_rules: vec![],
        allow_fallback_cv: true,
        allow_fallback_vv: true,
        split_ratio_onset: 0.5,
        split_ratio_coda: 0.5,
        max_consonant_duration_ms: 120,
        raw_csharp_source: Some(OFFICIAL_POLISH_CVC_CS.to_string()),
        source_github_url: Some("https://raw.githubusercontent.com/openutau/OpenUtau/master/OpenUtau.Plugin.Builtin/PolishCVCPhonemizer.cs".to_string()),
        custom_usings: vec![
            "using System;".to_string(),
            "using System.Collections.Generic;".to_string(),
            "using System.Linq;".to_string(),
            "using OpenUtau.Api;".to_string(),
        ],
        custom_class_fields: String::new(),
        custom_preprocess_code: String::new(),
        custom_postprocess_code: String::new(),
        custom_helper_methods: String::new(),
            test_cases: Vec::new(),
    }
}

pub fn create_thai_preset() -> PhonemizerProject {
    PhonemizerProject {
        name: "ThaiVCCVPhonemizer".to_string(),
        tag: "TH VCCV".to_string(),
        author: "Kuro & mim".to_string(),
        version: "1.0.0".to_string(),
        language_code: "TH".to_string(),
        description: "Official OpenUtau Thai VCCV Phonemizer.".to_string(),
        namespace: "OpenUtau.Plugin.Builtin".to_string(),
        base_class_type: PhonemeSystemType::SyllableBased,
        openutau_plugins_dir: default_openutau_plugins_path(),
        output_dll_name: "ThaiVCCVPhonemizer.dll".to_string(),
        vowels: vec![
            Vowel::new("a"),
            Vowel::new("i"),
            Vowel::new("u"),
            Vowel::new("e"),
            Vowel::new("o"),
            Vowel::new("v"),
            Vowel::new("x"),
            Vowel::new("@"),
        ],
        consonants: vec![
            Consonant::new("k", ConsonantType::Stop),
            Consonant::new("kh", ConsonantType::Stop),
            Consonant::new("ng", ConsonantType::Nasal),
            Consonant::new("c", ConsonantType::Affricate),
            Consonant::new("ch", ConsonantType::Affricate),
            Consonant::new("d", ConsonantType::Stop),
            Consonant::new("t", ConsonantType::Stop),
            Consonant::new("th", ConsonantType::Stop),
            Consonant::new("n", ConsonantType::Nasal),
            Consonant::new("b", ConsonantType::Stop),
            Consonant::new("p", ConsonantType::Stop),
            Consonant::new("ph", ConsonantType::Stop),
            Consonant::new("f", ConsonantType::Fricative),
            Consonant::new("m", ConsonantType::Nasal),
            Consonant::new("y", ConsonantType::Semivowel),
            Consonant::new("r", ConsonantType::Liquid),
            Consonant::new("l", ConsonantType::Liquid),
            Consonant::new("w", ConsonantType::Semivowel),
            Consonant::new("s", ConsonantType::Fricative),
            Consonant::new("h", ConsonantType::Fricative),
        ],
        onset_clusters: vec![],
        coda_clusters: vec![],
        pattern_rules: vec![],
        voice_color_and_pitch: VoiceColorAndPitchConfig::default(),
        syllabification_config: SyllabificationConfig::default(),
        dictionary_overrides: vec![],
        regex_rules: vec![],
        allow_fallback_cv: true,
        allow_fallback_vv: true,
        split_ratio_onset: 0.5,
        split_ratio_coda: 0.5,
        max_consonant_duration_ms: 120,
        raw_csharp_source: Some(OFFICIAL_THAI_VCCV_CS.to_string()),
        source_github_url: Some("https://raw.githubusercontent.com/openutau/OpenUtau/master/OpenUtau.Plugin.Builtin/ThaiVCCVPhonemizer.cs".to_string()),
        custom_usings: vec![
            "using System;".to_string(),
            "using System.Collections.Generic;".to_string(),
            "using System.Linq;".to_string(),
            "using OpenUtau.Api;".to_string(),
        ],
        custom_class_fields: String::new(),
        custom_preprocess_code: String::new(),
        custom_postprocess_code: String::new(),
        custom_helper_methods: String::new(),
            test_cases: Vec::new(),
    }
}

pub fn create_turkish_preset() -> PhonemizerProject {
    PhonemizerProject {
        name: "TurkishCVVCPhonemizer".to_string(),
        tag: "TR CVVC".to_string(),
        author: "mim & Berke".to_string(),
        version: "1.0.0".to_string(),
        language_code: "TR".to_string(),
        description: "Official OpenUtau Turkish CVVC Phonemizer.".to_string(),
        namespace: "OpenUtau.Plugin.Builtin".to_string(),
        base_class_type: PhonemeSystemType::SyllableBased,
        openutau_plugins_dir: default_openutau_plugins_path(),
        output_dll_name: "TurkishCVVCPhonemizer.dll".to_string(),
        vowels: vec![
            Vowel::new("a"),
            Vowel::new("e"),
            Vowel::new("i"),
            Vowel::new("I"),
            Vowel::new("o"),
            Vowel::new("O"),
            Vowel::new("u"),
            Vowel::new("U"),
        ],
        consonants: vec![
            Consonant::new("b", ConsonantType::Stop),
            Consonant::new("c", ConsonantType::Affricate),
            Consonant::new("C", ConsonantType::Affricate),
            Consonant::new("d", ConsonantType::Stop),
            Consonant::new("f", ConsonantType::Fricative),
            Consonant::new("g", ConsonantType::Stop),
            Consonant::new("G", ConsonantType::Stop),
            Consonant::new("h", ConsonantType::Fricative),
            Consonant::new("j", ConsonantType::Fricative),
            Consonant::new("k", ConsonantType::Stop),
            Consonant::new("l", ConsonantType::Liquid),
            Consonant::new("m", ConsonantType::Nasal),
            Consonant::new("n", ConsonantType::Nasal),
            Consonant::new("p", ConsonantType::Stop),
            Consonant::new("r", ConsonantType::Liquid),
            Consonant::new("s", ConsonantType::Fricative),
            Consonant::new("S", ConsonantType::Fricative),
            Consonant::new("t", ConsonantType::Stop),
            Consonant::new("v", ConsonantType::Fricative),
            Consonant::new("y", ConsonantType::Semivowel),
            Consonant::new("z", ConsonantType::Fricative),
        ],
        onset_clusters: vec![],
        coda_clusters: vec![],
        pattern_rules: vec![],
        voice_color_and_pitch: VoiceColorAndPitchConfig::default(),
        syllabification_config: SyllabificationConfig::default(),
        dictionary_overrides: vec![],
        regex_rules: vec![],
        allow_fallback_cv: true,
        allow_fallback_vv: true,
        split_ratio_onset: 0.5,
        split_ratio_coda: 0.5,
        max_consonant_duration_ms: 120,
        raw_csharp_source: Some(OFFICIAL_TURKISH_CVVC_CS.to_string()),
        source_github_url: Some("https://raw.githubusercontent.com/openutau/OpenUtau/master/OpenUtau.Plugin.Builtin/TurkishCVVCPhonemizer.cs".to_string()),
        custom_usings: vec![
            "using System;".to_string(),
            "using System.Collections.Generic;".to_string(),
            "using System.Linq;".to_string(),
            "using OpenUtau.Api;".to_string(),
        ],
        custom_class_fields: String::new(),
        custom_preprocess_code: String::new(),
        custom_postprocess_code: String::new(),
        custom_helper_methods: String::new(),
            test_cases: Vec::new(),
    }
}

pub fn create_vietnamese_preset() -> PhonemizerProject {
    PhonemizerProject {
        name: "VietnameseCVVCPhonemizer".to_string(),
        tag: "VI CVVC".to_string(),
        author: "mim & kuro".to_string(),
        version: "1.0.0".to_string(),
        language_code: "VI".to_string(),
        description: "Official OpenUtau Vietnamese CVVC Phonemizer.".to_string(),
        namespace: "OpenUtau.Plugin.Builtin".to_string(),
        base_class_type: PhonemeSystemType::SyllableBased,
        openutau_plugins_dir: default_openutau_plugins_path(),
        output_dll_name: "VietnameseCVVCPhonemizer.dll".to_string(),
        vowels: vec![
            Vowel::new("a"),
            Vowel::new("e"),
            Vowel::new("i"),
            Vowel::new("o"),
            Vowel::new("u"),
            Vowel::new("w"),
            Vowel::new("ow"),
            Vowel::new("aw"),
            Vowel::new("aa"),
            Vowel::new("ee"),
            Vowel::new("oo"),
        ],
        consonants: vec![
            Consonant::new("b", ConsonantType::Stop),
            Consonant::new("c", ConsonantType::Stop),
            Consonant::new("ch", ConsonantType::Affricate),
            Consonant::new("d", ConsonantType::Stop),
            Consonant::new("dd", ConsonantType::Stop),
            Consonant::new("g", ConsonantType::Stop),
            Consonant::new("gh", ConsonantType::Stop),
            Consonant::new("gi", ConsonantType::Fricative),
            Consonant::new("h", ConsonantType::Fricative),
            Consonant::new("k", ConsonantType::Stop),
            Consonant::new("kh", ConsonantType::Fricative),
            Consonant::new("l", ConsonantType::Liquid),
            Consonant::new("m", ConsonantType::Nasal),
            Consonant::new("n", ConsonantType::Nasal),
            Consonant::new("ng", ConsonantType::Nasal),
            Consonant::new("ngh", ConsonantType::Nasal),
            Consonant::new("nh", ConsonantType::Nasal),
            Consonant::new("p", ConsonantType::Stop),
            Consonant::new("ph", ConsonantType::Fricative),
            Consonant::new("qu", ConsonantType::Stop),
            Consonant::new("r", ConsonantType::Liquid),
            Consonant::new("s", ConsonantType::Fricative),
            Consonant::new("t", ConsonantType::Stop),
            Consonant::new("th", ConsonantType::Stop),
            Consonant::new("tr", ConsonantType::Affricate),
            Consonant::new("v", ConsonantType::Fricative),
            Consonant::new("x", ConsonantType::Fricative),
        ],
        onset_clusters: vec![],
        coda_clusters: vec![],
        pattern_rules: vec![],
        voice_color_and_pitch: VoiceColorAndPitchConfig::default(),
        syllabification_config: SyllabificationConfig::default(),
        dictionary_overrides: vec![],
        regex_rules: vec![],
        allow_fallback_cv: true,
        allow_fallback_vv: true,
        split_ratio_onset: 0.5,
        split_ratio_coda: 0.5,
        max_consonant_duration_ms: 120,
        raw_csharp_source: Some(OFFICIAL_VIETNAMESE_CVVC_CS.to_string()),
        source_github_url: Some("https://raw.githubusercontent.com/openutau/OpenUtau/master/OpenUtau.Plugin.Builtin/VietnameseCVVCPhonemizer.cs".to_string()),
        custom_usings: vec![
            "using System;".to_string(),
            "using System.Collections.Generic;".to_string(),
            "using System.Linq;".to_string(),
            "using OpenUtau.Api;".to_string(),
        ],
        custom_class_fields: String::new(),
        custom_preprocess_code: String::new(),
        custom_postprocess_code: String::new(),
        custom_helper_methods: String::new(),
            test_cases: Vec::new(),
    }
}

pub fn create_latin_preset() -> PhonemizerProject {
    PhonemizerProject {
        name: "LatinDiphonePhonemizer".to_string(),
        tag: "LA DIPHONE".to_string(),
        author: "stakira".to_string(),
        version: "1.0.0".to_string(),
        language_code: "LA".to_string(),
        description: "Official OpenUtau Latin Diphone Phonemizer.".to_string(),
        namespace: "OpenUtau.Plugin.Builtin".to_string(),
        base_class_type: PhonemeSystemType::CustomDirect,
        openutau_plugins_dir: default_openutau_plugins_path(),
        output_dll_name: "LatinDiphonePhonemizer.dll".to_string(),
        vowels: vec![
            Vowel::new("a"),
            Vowel::new("e"),
            Vowel::new("i"),
            Vowel::new("o"),
            Vowel::new("u"),
            Vowel::new("y"),
        ],
        consonants: vec![
            Consonant::new("b", ConsonantType::Stop),
            Consonant::new("c", ConsonantType::Stop),
            Consonant::new("d", ConsonantType::Stop),
            Consonant::new("f", ConsonantType::Fricative),
            Consonant::new("g", ConsonantType::Stop),
            Consonant::new("h", ConsonantType::Fricative),
            Consonant::new("k", ConsonantType::Stop),
            Consonant::new("l", ConsonantType::Liquid),
            Consonant::new("m", ConsonantType::Nasal),
            Consonant::new("n", ConsonantType::Nasal),
            Consonant::new("p", ConsonantType::Stop),
            Consonant::new("q", ConsonantType::Stop),
            Consonant::new("r", ConsonantType::Liquid),
            Consonant::new("s", ConsonantType::Fricative),
            Consonant::new("t", ConsonantType::Stop),
            Consonant::new("v", ConsonantType::Fricative),
            Consonant::new("x", ConsonantType::Fricative),
            Consonant::new("z", ConsonantType::Fricative),
        ],
        onset_clusters: vec![],
        coda_clusters: vec![],
        pattern_rules: vec![],
        voice_color_and_pitch: VoiceColorAndPitchConfig::default(),
        syllabification_config: SyllabificationConfig::default(),
        dictionary_overrides: vec![],
        regex_rules: vec![],
        allow_fallback_cv: true,
        allow_fallback_vv: true,
        split_ratio_onset: 0.5,
        split_ratio_coda: 0.5,
        max_consonant_duration_ms: 120,
        raw_csharp_source: Some(OFFICIAL_LATIN_DIPHONE_CS.to_string()),
        source_github_url: Some("https://raw.githubusercontent.com/openutau/OpenUtau/master/OpenUtau.Plugin.Builtin/LatinDiphonePhonemizer.cs".to_string()),
        custom_usings: vec![
            "using System;".to_string(),
            "using System.Collections.Generic;".to_string(),
            "using System.Linq;".to_string(),
            "using OpenUtau.Api;".to_string(),
        ],
        custom_class_fields: String::new(),
        custom_preprocess_code: String::new(),
        custom_postprocess_code: String::new(),
        custom_helper_methods: String::new(),
            test_cases: Vec::new(),
    }
}
