use crate::models::*;

pub const OFFICIAL_PORTUGUESE_CS: &str = include_str!("../../official_openutau_sources/BrazilianPortugueseCVCPhonemizer.cs");

pub fn create_portuguese_preset() -> PhonemizerProject {
    let mut project = PhonemizerProject {
        name: "BrazilianPortugueseCVCPhonemizer".to_string(),
        tag: "PT-BR CVC".to_string(),
        author: "HAI-D".to_string(),
        version: "1.0.0".to_string(),
        language_code: "PT".to_string(),
        description: "Official OpenUtau Brazilian Portuguese CVC Phonemizer by HAI-D. Connotation: BRAPA, Main Accent: Neutral. Supported Alias: -C, -V, C-, V-, -CV, VC-, CV, VC, V, VV, _V".to_string(),
        namespace: "OpenUtau.Plugin.Builtin".to_string(),
        base_class_type: PhonemeSystemType::SyllableBased,
        openutau_plugins_dir: default_openutau_plugins_path(),
        output_dll_name: "BrazilianPortugueseCVCPhonemizer.dll".to_string(),
        vowels: vec![

            Vowel { symbol: "a".to_string(), ipa: "a".to_string(), aliases: vec!["a".to_string()], is_nasal: false, is_diphthong: false, is_triphthong: false, second_vowel: None, third_vowel: None, diphthong_split_ratio: 0.65, end_glide: Some("a -".to_string()), glottal_start_alias: None, elongation_symbol: None, stress_variants: vec![], color_overrides: vec![] },
            Vowel { symbol: "oa".to_string(), ipa: "ɔa".to_string(), aliases: vec![], is_nasal: false, is_diphthong: true, is_triphthong: false, second_vowel: Some("a".to_string()), third_vowel: None, diphthong_split_ratio: 0.65, end_glide: Some("a -".to_string()), glottal_start_alias: None, elongation_symbol: None, stress_variants: vec![], color_overrides: vec![] },
            Vowel { symbol: "ah".to_string(), ipa: "a".to_string(), aliases: vec![], is_nasal: false, is_diphthong: false, is_triphthong: false, second_vowel: None, third_vowel: None, diphthong_split_ratio: 0.65, end_glide: Some("ah -".to_string()), glottal_start_alias: None, elongation_symbol: None, stress_variants: vec![], color_overrides: vec![] },
            Vowel { symbol: "ahn".to_string(), ipa: "ɐ̃".to_string(), aliases: vec![], is_nasal: true, is_diphthong: false, is_triphthong: false, second_vowel: None, third_vowel: None, diphthong_split_ratio: 0.65, end_glide: Some("ahn -".to_string()), glottal_start_alias: None, elongation_symbol: None, stress_variants: vec![], color_overrides: vec![] },
            Vowel { symbol: "ax".to_string(), ipa: "ə".to_string(), aliases: vec![], is_nasal: false, is_diphthong: false, is_triphthong: false, second_vowel: None, third_vowel: None, diphthong_split_ratio: 0.65, end_glide: Some("ax -".to_string()), glottal_start_alias: None, elongation_symbol: None, stress_variants: vec![], color_overrides: vec![] },
            Vowel { symbol: "an".to_string(), ipa: "ɐ̃".to_string(), aliases: vec!["ã".to_string()], is_nasal: true, is_diphthong: false, is_triphthong: false, second_vowel: None, third_vowel: None, diphthong_split_ratio: 0.65, end_glide: Some("an -".to_string()), glottal_start_alias: None, elongation_symbol: None, stress_variants: vec![], color_overrides: vec![] },
            Vowel { symbol: "e".to_string(), ipa: "e".to_string(), aliases: vec!["ê".to_string()], is_nasal: false, is_diphthong: false, is_triphthong: false, second_vowel: None, third_vowel: None, diphthong_split_ratio: 0.65, end_glide: Some("e -".to_string()), glottal_start_alias: None, elongation_symbol: None, stress_variants: vec![], color_overrides: vec![] },
            Vowel { symbol: "en".to_string(), ipa: "ẽ".to_string(), aliases: vec!["em".to_string()], is_nasal: true, is_diphthong: false, is_triphthong: false, second_vowel: None, third_vowel: None, diphthong_split_ratio: 0.65, end_glide: Some("en -".to_string()), glottal_start_alias: None, elongation_symbol: None, stress_variants: vec![], color_overrides: vec![] },
            Vowel { symbol: "eh".to_string(), ipa: "ɛ".to_string(), aliases: vec!["é".to_string()], is_nasal: false, is_diphthong: false, is_triphthong: false, second_vowel: None, third_vowel: None, diphthong_split_ratio: 0.65, end_glide: Some("eh -".to_string()), glottal_start_alias: None, elongation_symbol: None, stress_variants: vec![], color_overrides: vec![] },
            Vowel { symbol: "ehn".to_string(), ipa: "ɛ̃".to_string(), aliases: vec![], is_nasal: true, is_diphthong: false, is_triphthong: false, second_vowel: None, third_vowel: None, diphthong_split_ratio: 0.65, end_glide: Some("ehn -".to_string()), glottal_start_alias: None, elongation_symbol: None, stress_variants: vec![], color_overrides: vec![] },
            Vowel { symbol: "ae".to_string(), ipa: "aɛ".to_string(), aliases: vec![], is_nasal: false, is_diphthong: true, is_triphthong: false, second_vowel: Some("eh".to_string()), third_vowel: None, diphthong_split_ratio: 0.65, end_glide: Some("ae -".to_string()), glottal_start_alias: None, elongation_symbol: None, stress_variants: vec![], color_overrides: vec![] },
            Vowel { symbol: "aen".to_string(), ipa: "aɛ̃".to_string(), aliases: vec![], is_nasal: true, is_diphthong: true, is_triphthong: false, second_vowel: Some("ehn".to_string()), third_vowel: None, diphthong_split_ratio: 0.65, end_glide: Some("aen -".to_string()), glottal_start_alias: None, elongation_symbol: None, stress_variants: vec![], color_overrides: vec![] },
            Vowel { symbol: "i".to_string(), ipa: "i".to_string(), aliases: vec![], is_nasal: false, is_diphthong: false, is_triphthong: false, second_vowel: None, third_vowel: None, diphthong_split_ratio: 0.65, end_glide: Some("i -".to_string()), glottal_start_alias: None, elongation_symbol: None, stress_variants: vec![], color_overrides: vec![] },
            Vowel { symbol: "in".to_string(), ipa: "ĩ".to_string(), aliases: vec!["im".to_string()], is_nasal: true, is_diphthong: false, is_triphthong: false, second_vowel: None, third_vowel: None, diphthong_split_ratio: 0.65, end_glide: Some("in -".to_string()), glottal_start_alias: None, elongation_symbol: None, stress_variants: vec![], color_overrides: vec![] },
            Vowel { symbol: "i0".to_string(), ipa: "i̥".to_string(), aliases: vec![], is_nasal: false, is_diphthong: false, is_triphthong: false, second_vowel: None, third_vowel: None, diphthong_split_ratio: 0.65, end_glide: Some("i0 -".to_string()), glottal_start_alias: None, elongation_symbol: None, stress_variants: vec![], color_overrides: vec![] },
            Vowel { symbol: "o".to_string(), ipa: "o".to_string(), aliases: vec!["ô".to_string()], is_nasal: false, is_diphthong: false, is_triphthong: false, second_vowel: None, third_vowel: None, diphthong_split_ratio: 0.65, end_glide: Some("o -".to_string()), glottal_start_alias: None, elongation_symbol: None, stress_variants: vec![], color_overrides: vec![] },
            Vowel { symbol: "on".to_string(), ipa: "õ".to_string(), aliases: vec!["om".to_string()], is_nasal: true, is_diphthong: false, is_triphthong: false, second_vowel: None, third_vowel: None, diphthong_split_ratio: 0.65, end_glide: Some("on -".to_string()), glottal_start_alias: None, elongation_symbol: None, stress_variants: vec![], color_overrides: vec![] },
            Vowel { symbol: "oh".to_string(), ipa: "ɔ".to_string(), aliases: vec!["ó".to_string()], is_nasal: false, is_diphthong: false, is_triphthong: false, second_vowel: None, third_vowel: None, diphthong_split_ratio: 0.65, end_glide: Some("oh -".to_string()), glottal_start_alias: None, elongation_symbol: None, stress_variants: vec![], color_overrides: vec![] },
            Vowel { symbol: "ohn".to_string(), ipa: "ɔ̃".to_string(), aliases: vec![], is_nasal: true, is_diphthong: false, is_triphthong: false, second_vowel: None, third_vowel: None, diphthong_split_ratio: 0.65, end_glide: Some("ohn -".to_string()), glottal_start_alias: None, elongation_symbol: None, stress_variants: vec![], color_overrides: vec![] },
            Vowel { symbol: "u".to_string(), ipa: "u".to_string(), aliases: vec![], is_nasal: false, is_diphthong: false, is_triphthong: false, second_vowel: None, third_vowel: None, diphthong_split_ratio: 0.65, end_glide: Some("u -".to_string()), glottal_start_alias: None, elongation_symbol: None, stress_variants: vec![], color_overrides: vec![] },
            Vowel { symbol: "un".to_string(), ipa: "ũ".to_string(), aliases: vec!["um".to_string()], is_nasal: true, is_diphthong: false, is_triphthong: false, second_vowel: None, third_vowel: None, diphthong_split_ratio: 0.65, end_glide: Some("un -".to_string()), glottal_start_alias: None, elongation_symbol: None, stress_variants: vec![], color_overrides: vec![] },
            Vowel { symbol: "u0".to_string(), ipa: "u̥".to_string(), aliases: vec![], is_nasal: false, is_diphthong: false, is_triphthong: false, second_vowel: None, third_vowel: None, diphthong_split_ratio: 0.65, end_glide: Some("u0 -".to_string()), glottal_start_alias: None, elongation_symbol: None, stress_variants: vec![], color_overrides: vec![] },
        ],
        consonants: vec![

            Consonant::new("b", ConsonantType::Stop),
            Consonant::new("bv", ConsonantType::Stop),
            Consonant::new("ch", ConsonantType::Affricate),
            Consonant::new("d", ConsonantType::Stop),
            Consonant::new("dj", ConsonantType::Affricate),
            Consonant::new("f", ConsonantType::Fricative),
            Consonant::new("g", ConsonantType::Stop),
            Consonant::new("gv", ConsonantType::Stop),
            Consonant::new("h", ConsonantType::Fricative),
            Consonant::new("hr", ConsonantType::Fricative),
            Consonant::new("k", ConsonantType::Stop),
            Consonant::new("l", ConsonantType::Liquid),
            Consonant::new("l0", ConsonantType::Liquid),
            Consonant::new("lh", ConsonantType::Liquid),
            Consonant::new("m", ConsonantType::Nasal),
            Consonant::new("n", ConsonantType::Nasal),
            Consonant::new("ng", ConsonantType::Nasal),
            Consonant::new("nh", ConsonantType::Nasal),
            Consonant::new("p", ConsonantType::Stop),
            Consonant::new("r", ConsonantType::Liquid),
            Consonant::new("rr", ConsonantType::Liquid),
            Consonant::new("rw", ConsonantType::Liquid),
            Consonant::new("s", ConsonantType::Fricative),
            Consonant::new("sh", ConsonantType::Fricative),
            Consonant::new("t", ConsonantType::Stop),
            Consonant::new("v", ConsonantType::Fricative),
            Consonant::new("w", ConsonantType::Semivowel),
            Consonant::new("x", ConsonantType::Fricative),
            Consonant::new("y", ConsonantType::Semivowel),
            Consonant::new("z", ConsonantType::Fricative),
            Consonant::new("rh", ConsonantType::Liquid),
        ],
        onset_clusters: vec![
            ConsonantCluster::new("br", vec!["b".to_string(), "r".to_string()], true),
            ConsonantCluster::new("bl", vec!["b".to_string(), "l".to_string()], true),
            ConsonantCluster::new("cr", vec!["k".to_string(), "r".to_string()], true),
            ConsonantCluster::new("cl", vec!["k".to_string(), "l".to_string()], true),
            ConsonantCluster::new("dr", vec!["d".to_string(), "r".to_string()], true),
            ConsonantCluster::new("fr", vec!["f".to_string(), "r".to_string()], true),
            ConsonantCluster::new("fl", vec!["f".to_string(), "l".to_string()], true),
            ConsonantCluster::new("gr", vec!["g".to_string(), "r".to_string()], true),
            ConsonantCluster::new("gl", vec!["g".to_string(), "l".to_string()], true),
            ConsonantCluster::new("pr", vec!["p".to_string(), "r".to_string()], true),
            ConsonantCluster::new("pl", vec!["p".to_string(), "l".to_string()], true),
            ConsonantCluster::new("tr", vec!["t".to_string(), "r".to_string()], true),
            ConsonantCluster::new("tl", vec!["t".to_string(), "l".to_string()], true),
            ConsonantCluster::new("vr", vec!["v".to_string(), "r".to_string()], true),
            ConsonantCluster::new("vl", vec!["v".to_string(), "l".to_string()], true),
        ],
        coda_clusters: vec![],
        pattern_rules: vec![
            PhoneticPatternRule { pattern_type: PatternType::RestingStartVowel, template: "- {vowel}".to_string(), enabled: true, priority: 10, fallback_template: Some("{vowel}".to_string()), min_pitch_note: None, max_pitch_note: None, color_filter: None },
            PhoneticPatternRule { pattern_type: PatternType::RestingStartConsonant, template: "-{consonant} {vowel}".to_string(), enabled: true, priority: 10, fallback_template: Some("{consonant} {vowel}".to_string()), min_pitch_note: None, max_pitch_note: None, color_filter: None },
            PhoneticPatternRule { pattern_type: PatternType::VCV, template: "{prev_vowel} {consonant}{vowel}".to_string(), enabled: true, priority: 9, fallback_template: Some("{consonant} {vowel}".to_string()), min_pitch_note: None, max_pitch_note: None, color_filter: None },
            PhoneticPatternRule { pattern_type: PatternType::CV, template: "{consonant} {vowel}".to_string(), enabled: true, priority: 8, fallback_template: None, min_pitch_note: None, max_pitch_note: None, color_filter: None },
            PhoneticPatternRule { pattern_type: PatternType::VC, template: "{prev_vowel} {consonant}-".to_string(), enabled: true, priority: 7, fallback_template: Some("{prev_vowel} {consonant}".to_string()), min_pitch_note: None, max_pitch_note: None, color_filter: None },
            PhoneticPatternRule { pattern_type: PatternType::VV, template: "{prev_vowel} {vowel}".to_string(), enabled: true, priority: 6, fallback_template: Some("_{vowel}".to_string()), min_pitch_note: None, max_pitch_note: None, color_filter: None },
            PhoneticPatternRule { pattern_type: PatternType::EndingVowelGlide, template: "{vowel} -".to_string(), enabled: true, priority: 5, fallback_template: None, min_pitch_note: None, max_pitch_note: None, color_filter: None },
            PhoneticPatternRule { pattern_type: PatternType::EndingConsonantCoda, template: "{consonant} -".to_string(), enabled: true, priority: 5, fallback_template: Some("{consonant}".to_string()), min_pitch_note: None, max_pitch_note: None, color_filter: None },
        ],
        voice_color_and_pitch: VoiceColorAndPitchConfig::default(),
        syllabification_config: SyllabificationConfig::default(),
        dictionary_overrides: vec![
            DictionaryOverride::new("você", vec!["v".to_string(), "o".to_string(), "s".to_string(), "e".to_string()]),
            DictionaryOverride::new("voce", vec!["v".to_string(), "o".to_string(), "s".to_string(), "e".to_string()]),
            DictionaryOverride::new("me", vec!["m".to_string(), "i".to_string()]),
            DictionaryOverride::new("deu", vec!["d".to_string(), "e".to_string(), "u".to_string()]),
            DictionaryOverride::new("amor", vec!["a".to_string(), "m".to_string(), "o".to_string(), "r".to_string()]),
            DictionaryOverride::new("no", vec!["n".to_string(), "u".to_string()]),
            DictionaryOverride::new("na", vec!["n".to_string(), "a".to_string()]),
            DictionaryOverride::new("coração", vec!["k".to_string(), "o".to_string(), "r".to_string(), "a".to_string(), "s".to_string(), "an".to_string(), "u".to_string()]),
            DictionaryOverride::new("coracao", vec!["k".to_string(), "o".to_string(), "r".to_string(), "a".to_string(), "s".to_string(), "an".to_string(), "u".to_string()]),
            DictionaryOverride::new("não", vec!["n".to_string(), "an".to_string(), "u".to_string()]),
            DictionaryOverride::new("nao", vec!["n".to_string(), "an".to_string(), "u".to_string()]),
            DictionaryOverride::new("também", vec!["t".to_string(), "an".to_string(), "b".to_string(), "en".to_string(), "i".to_string()]),
            DictionaryOverride::new("tambem", vec!["t".to_string(), "an".to_string(), "b".to_string(), "en".to_string(), "i".to_string()]),
            DictionaryOverride::new("saudade", vec!["s".to_string(), "a".to_string(), "u".to_string(), "d".to_string(), "a".to_string(), "dj".to_string(), "i".to_string()]),
            DictionaryOverride::new("tudo", vec!["t".to_string(), "u".to_string(), "d".to_string(), "u".to_string()]),
            DictionaryOverride::new("vida", vec!["v".to_string(), "i".to_string(), "d".to_string(), "a".to_string()]),
            DictionaryOverride::new("luz", vec!["l", "u", "s"].iter().map(|s| s.to_string()).collect()),
            DictionaryOverride::new("sol", vec!["s", "o", "w"].iter().map(|s| s.to_string()).collect()),
            DictionaryOverride::new("dia", vec!["dj", "i", "a"].iter().map(|s| s.to_string()).collect()),
            DictionaryOverride::new("noite", vec!["n", "o", "i", "tS", "i"].iter().map(|s| s.to_string()).collect()),
            DictionaryOverride::new("céu", vec!["s", "eh", "u"].iter().map(|s| s.to_string()).collect()),
            DictionaryOverride::new("ceu", vec!["s", "eh", "u"].iter().map(|s| s.to_string()).collect()),
            DictionaryOverride::new("mundo", vec!["m", "un", "d", "u"].iter().map(|s| s.to_string()).collect()),
            DictionaryOverride::new("bem", vec!["b", "en", "i"].iter().map(|s| s.to_string()).collect()),
            DictionaryOverride::new("bom", vec!["b", "on"].iter().map(|s| s.to_string()).collect()),
            DictionaryOverride::new("sim", vec!["s", "in"].iter().map(|s| s.to_string()).collect()),
            DictionaryOverride::new("vem", vec!["v", "en", "i"].iter().map(|s| s.to_string()).collect()),
            DictionaryOverride::new("pra", vec!["p", "r", "a"].iter().map(|s| s.to_string()).collect()),
            DictionaryOverride::new("com", vec!["k", "on"].iter().map(|s| s.to_string()).collect()),
            DictionaryOverride::new("te", vec!["tS", "i"].iter().map(|s| s.to_string()).collect()),
            DictionaryOverride::new("se", vec!["s", "i"].iter().map(|s| s.to_string()).collect()),
            DictionaryOverride::new("que", vec!["k", "i"].iter().map(|s| s.to_string()).collect()),
        ],
        regex_rules: vec![

            RegexRule::new("G2P E -> eh", "E", "eh", 1),
            RegexRule::new("G2P O -> oh", "O", "oh", 2),
            RegexRule::new("G2P a~ -> an", "a~", "an", 3),
            RegexRule::new("G2P e~ -> en", "e~", "en", 4),
            RegexRule::new("G2P i~ -> in", "i~", "in", 5),
            RegexRule::new("G2P o~ -> on", "o~", "on", 6),
            RegexRule::new("G2P u~ -> un", "u~", "un", 7),
            RegexRule::new("G2P tS -> ch", "tS", "ch", 8),
            RegexRule::new("G2P dZ -> dj", "dZ", "dj", 9),
            RegexRule::new("G2P X -> h", "X", "h", 10),
            RegexRule::new("G2P R -> h", "R", "h", 11),
            RegexRule::new("G2P Z -> j", "Z", "j", 12),
            RegexRule::new("G2P L -> lh", "L", "lh", 13),
            RegexRule::new("G2P J -> nh", "J", "nh", 14),
            RegexRule::new("G2P S -> sh", "S", "sh", 15),
            RegexRule::new("G2P w~ -> w", "w~", "w", 16),
            RegexRule::new("G2P j -> y", "j", "y", 17),
            RegexRule::new("G2P j~ -> y", "j~", "y", 18),
        ],
        allow_fallback_cv: true,
        allow_fallback_vv: true,
        split_ratio_onset: 0.5,
        split_ratio_coda: 0.5,
        max_consonant_duration_ms: 120,
        raw_csharp_source: Some(OFFICIAL_PORTUGUESE_CS.to_string()),
        source_github_url: Some("https://raw.githubusercontent.com/openutau/OpenUtau/master/OpenUtau.Plugin.Builtin/BrazilianPortugueseCVCPhonemizer.cs".to_string()),
        custom_usings: vec![
            "using System;".to_string(),
            "using System.Collections.Generic;".to_string(),
            "using System.Linq;".to_string(),
            "using OpenUtau.Api;".to_string(),
            "using OpenUtau.Core.G2p;".to_string(),
        ],
        custom_class_fields: String::new(),
        custom_preprocess_code: String::new(),
        custom_postprocess_code: String::new(),
        custom_helper_methods: String::new(),
            test_cases: Vec::new(),
    };

    for c in &mut project.consonants {
        if ["r"].contains(&c.symbol.as_str()) {
            c.timing_ratio = 0.75;
        }
        if ["s", "sh"].contains(&c.symbol.as_str()) {
            c.timing_ratio = 1.5;
        }
        if ["b", "ch", "d", "dj", "g", "k", "p", "t"].contains(&c.symbol.as_str()) {
            c.consonant_type = ConsonantType::Stop;
        }
        if ["l", "m", "n", "r", "s", "sh", "z", "rh", "w", "y"].contains(&c.symbol.as_str()) {
            c.can_be_coda = true;
        }
    }

    project
}
