use crate::models::*;

pub const OFFICIAL_RUSSIAN_CVC_CS: &str = include_str!("../../official_openutau_sources/RussianCVCPhonemizer.cs");

pub fn create_russian_cvc_preset() -> PhonemizerProject {
    PhonemizerProject {
        name: "RussianCVCPhonemizer".to_string(),
        tag: "RU CVC".to_string(),
        author: "Heiden.BZR".to_string(),
        version: "1.0.0".to_string(),
        language_code: "RU".to_string(),
        description: "Official OpenUtau Russian CVC Phonemizer by Heiden.BZR with hard and soft palatalized consonants, burst timing, and glide fallbacks.".to_string(),
        namespace: "OpenUtau.Plugin.Builtin".to_string(),
        base_class_type: PhonemeSystemType::RussianCVC,
        openutau_plugins_dir: default_openutau_plugins_path(),
        output_dll_name: "RussianCVCPhonemizer.dll".to_string(),
        vowels: vec![
            Vowel::new("a"),
            Vowel::new("e"),
            Vowel::new("o"),
            Vowel::new("u"),
            Vowel::new("y"),
            Vowel::new("i"),
            Vowel::new("M"),
            Vowel::new("N"),
        ],
        consonants: vec![
            Consonant::new("b", ConsonantType::Stop),
            Consonant::new("b'", ConsonantType::Stop),
            Consonant::new("v", ConsonantType::Fricative),
            Consonant::new("v'", ConsonantType::Fricative),
            Consonant::new("g", ConsonantType::Stop),
            Consonant::new("g'", ConsonantType::Stop),
            Consonant::new("d", ConsonantType::Stop),
            Consonant::new("d'", ConsonantType::Stop),
            Consonant::new("z", ConsonantType::Fricative),
            Consonant::new("z'", ConsonantType::Fricative),
            Consonant::new("k", ConsonantType::Stop),
            Consonant::new("k'", ConsonantType::Stop),
            Consonant::new("l", ConsonantType::Liquid),
            Consonant::new("l'", ConsonantType::Liquid),
            Consonant::new("m", ConsonantType::Nasal),
            Consonant::new("m'", ConsonantType::Nasal),
            Consonant::new("n", ConsonantType::Nasal),
            Consonant::new("n'", ConsonantType::Nasal),
            Consonant::new("p", ConsonantType::Stop),
            Consonant::new("p'", ConsonantType::Stop),
            Consonant::new("r", ConsonantType::Liquid),
            Consonant::new("r'", ConsonantType::Liquid),
            Consonant::new("s", ConsonantType::Fricative),
            Consonant::new("s'", ConsonantType::Fricative),
            Consonant::new("t", ConsonantType::Stop),
            Consonant::new("t'", ConsonantType::Stop),
            Consonant::new("f", ConsonantType::Fricative),
            Consonant::new("f'", ConsonantType::Fricative),
            Consonant::new("h", ConsonantType::Fricative),
            Consonant::new("h'", ConsonantType::Fricative),
            Consonant::new("w", ConsonantType::Semivowel),
            Consonant::new("w'", ConsonantType::Semivowel),
            Consonant::new("j", ConsonantType::Semivowel),
            Consonant::new("~", ConsonantType::Semivowel),
            Consonant::new("c", ConsonantType::Affricate),
            Consonant::new("4'", ConsonantType::Affricate),
        ],
        onset_clusters: vec![],
        coda_clusters: vec![],
        pattern_rules: vec![],
        voice_color_and_pitch: VoiceColorAndPitchConfig::default(),
        syllabification_config: SyllabificationConfig::default(),
        dictionary_overrides: vec![],
        regex_rules: vec![
            RegexRule::new("G2P ch -> 4'", "ch", "4'", 1),
            RegexRule::new("G2P sh -> w", "sh", "w", 2),
            RegexRule::new("G2P sch -> w'", "sch", "w'", 3),
            RegexRule::new("G2P zh -> j", "zh", "j", 4),
        ],
        allow_fallback_cv: true,
        allow_fallback_vv: true,
        split_ratio_onset: 0.5,
        split_ratio_coda: 0.5,
        max_consonant_duration_ms: 120,
        raw_csharp_source: Some(OFFICIAL_RUSSIAN_CVC_CS.to_string()),
        source_github_url: Some("https://raw.githubusercontent.com/openutau/OpenUtau/master/OpenUtau.Plugin.Builtin/RussianCVCPhonemizer.cs".to_string()),
        custom_usings: vec![
            "using System;".to_string(),
            "using System.Collections.Generic;".to_string(),
            "using System.Linq;".to_string(),
            "using OpenUtau.Api;".to_string(),
            "using OpenUtau.Core.G2p;".to_string(),
        ],
        custom_class_fields: String::new(),
        custom_preprocess_code: String::new(),
        custom_postprocess_code: String::new(),
        custom_helper_methods: String::new(),
            test_cases: Vec::new(),
    }
}
