use crate::models::*;

pub const OFFICIAL_SPANISH_SYLLABLE_CS: &str = include_str!("../../official_openutau_sources/SpanishSyllableBasedPhonemizer.cs");
pub const OFFICIAL_SPANISH_VCCV_CS: &str = include_str!("../../official_openutau_sources/SpanishVCCVPhonemizer.cs");

pub fn create_spanish_preset() -> PhonemizerProject {
    PhonemizerProject {
        name: "SpanishSyllableBasedPhonemizer".to_string(),
        tag: "ES SYL".to_string(),
        author: "Lotte V".to_string(),
        version: "1.0.0".to_string(),
        language_code: "ES".to_string(),
        description: "Official OpenUtau Spanish Syllable-Based Phonemizer by Lotte V. Supports CVVC, VCV, seseo, eñe fallbacks, and consonant clusters.".to_string(),
        namespace: "OpenUtau.Plugin.Builtin".to_string(),
        base_class_type: PhonemeSystemType::SyllableBased,
        openutau_plugins_dir: default_openutau_plugins_path(),
        output_dll_name: "SpanishSyllableBasedPhonemizer.dll".to_string(),
        vowels: vec![
            Vowel { symbol: "a".to_string(), ipa: "a".to_string(), aliases: vec!["á".to_string()], is_nasal: false, is_diphthong: false, is_triphthong: false, second_vowel: None, third_vowel: None, diphthong_split_ratio: 0.65, end_glide: Some("a -".to_string()), glottal_start_alias: None, elongation_symbol: None, stress_variants: vec![], color_overrides: vec![] },
            Vowel { symbol: "e".to_string(), ipa: "e".to_string(), aliases: vec!["é".to_string()], is_nasal: false, is_diphthong: false, is_triphthong: false, second_vowel: None, third_vowel: None, diphthong_split_ratio: 0.65, end_glide: Some("e -".to_string()), glottal_start_alias: None, elongation_symbol: None, stress_variants: vec![], color_overrides: vec![] },
            Vowel { symbol: "i".to_string(), ipa: "i".to_string(), aliases: vec!["í".to_string(), "y".to_string()], is_nasal: false, is_diphthong: false, is_triphthong: false, second_vowel: None, third_vowel: None, diphthong_split_ratio: 0.65, end_glide: Some("i -".to_string()), glottal_start_alias: None, elongation_symbol: None, stress_variants: vec![], color_overrides: vec![] },
            Vowel { symbol: "o".to_string(), ipa: "o".to_string(), aliases: vec!["ó".to_string()], is_nasal: false, is_diphthong: false, is_triphthong: false, second_vowel: None, third_vowel: None, diphthong_split_ratio: 0.65, end_glide: Some("o -".to_string()), glottal_start_alias: None, elongation_symbol: None, stress_variants: vec![], color_overrides: vec![] },
            Vowel { symbol: "u".to_string(), ipa: "u".to_string(), aliases: vec!["ú".to_string(), "ü".to_string()], is_nasal: false, is_diphthong: false, is_triphthong: false, second_vowel: None, third_vowel: None, diphthong_split_ratio: 0.65, end_glide: Some("u -".to_string()), glottal_start_alias: None, elongation_symbol: None, stress_variants: vec![], color_overrides: vec![] },
        ],
        consonants: vec![

            Consonant::new("b", ConsonantType::Stop),
            Consonant::new("ch", ConsonantType::Affricate),
            Consonant::new("d", ConsonantType::Stop),
            Consonant::new("dz", ConsonantType::Affricate),
            Consonant::new("f", ConsonantType::Fricative),
            Consonant::new("g", ConsonantType::Stop),
            Consonant::new("h", ConsonantType::Fricative),
            Consonant::new("hh", ConsonantType::Fricative),
            Consonant::new("j", ConsonantType::Fricative),
            Consonant::new("k", ConsonantType::Stop),
            Consonant::new("l", ConsonantType::Liquid),
            Consonant::new("ll", ConsonantType::Liquid),
            Consonant::new("m", ConsonantType::Nasal),
            Consonant::new("n", ConsonantType::Nasal),
            Consonant::new("nh", ConsonantType::Nasal),
            Consonant::new("p", ConsonantType::Stop),
            Consonant::new("r", ConsonantType::Liquid),
            Consonant::new("rr", ConsonantType::Liquid),
            Consonant::new("s", ConsonantType::Fricative),
            Consonant::new("sh", ConsonantType::Fricative),
            Consonant::new("t", ConsonantType::Stop),
            Consonant::new("ts", ConsonantType::Affricate),
            Consonant::new("w", ConsonantType::Semivowel),
            Consonant::new("y", ConsonantType::Semivowel),
            Consonant::new("z", ConsonantType::Fricative),
            Consonant::new("zz", ConsonantType::Fricative),
            Consonant::new("zh", ConsonantType::Fricative),
            Consonant::new("I", ConsonantType::Semivowel),
            Consonant::new("U", ConsonantType::Semivowel),
        ],
        onset_clusters: vec![
            ConsonantCluster::new("bl", vec!["b".to_string(), "l".to_string()], true),
            ConsonantCluster::new("br", vec!["b".to_string(), "r".to_string()], true),
            ConsonantCluster::new("dr", vec!["d".to_string(), "r".to_string()], true),
            ConsonantCluster::new("fl", vec!["f".to_string(), "l".to_string()], true),
            ConsonantCluster::new("fr", vec!["f".to_string(), "r".to_string()], true),
            ConsonantCluster::new("gl", vec!["g".to_string(), "l".to_string()], true),
            ConsonantCluster::new("gr", vec!["g".to_string(), "r".to_string()], true),
            ConsonantCluster::new("kl", vec!["k".to_string(), "l".to_string()], true),
            ConsonantCluster::new("kr", vec!["k".to_string(), "r".to_string()], true),
            ConsonantCluster::new("pl", vec!["p".to_string(), "l".to_string()], true),
            ConsonantCluster::new("pr", vec!["p".to_string(), "r".to_string()], true),
            ConsonantCluster::new("tr", vec!["t".to_string(), "r".to_string()], true),
        ],
        coda_clusters: vec![],
        pattern_rules: vec![
            PhoneticPatternRule { pattern_type: PatternType::RestingStartVowel, template: "- {vowel}".to_string(), enabled: true, priority: 10, fallback_template: Some("{vowel}".to_string()), min_pitch_note: None, max_pitch_note: None, color_filter: None },
            PhoneticPatternRule { pattern_type: PatternType::RestingStartConsonant, template: "- {consonant}{vowel}".to_string(), enabled: true, priority: 10, fallback_template: Some("{consonant}{vowel}".to_string()), min_pitch_note: None, max_pitch_note: None, color_filter: None },
            PhoneticPatternRule { pattern_type: PatternType::VCV, template: "{prev_vowel} {consonant}{vowel}".to_string(), enabled: true, priority: 9, fallback_template: Some("{consonant}{vowel}".to_string()), min_pitch_note: None, max_pitch_note: None, color_filter: None },
            PhoneticPatternRule { pattern_type: PatternType::CV, template: "{consonant}{vowel}".to_string(), enabled: true, priority: 8, fallback_template: None, min_pitch_note: None, max_pitch_note: None, color_filter: None },
            PhoneticPatternRule { pattern_type: PatternType::VC, template: "{prev_vowel} {consonant}".to_string(), enabled: true, priority: 7, fallback_template: None, min_pitch_note: None, max_pitch_note: None, color_filter: None },
            PhoneticPatternRule { pattern_type: PatternType::VV, template: "{prev_vowel} {vowel}".to_string(), enabled: true, priority: 6, fallback_template: Some("{vowel}".to_string()), min_pitch_note: None, max_pitch_note: None, color_filter: None },
            PhoneticPatternRule { pattern_type: PatternType::EndingVowelGlide, template: "{vowel} -".to_string(), enabled: true, priority: 5, fallback_template: None, min_pitch_note: None, max_pitch_note: None, color_filter: None },
        ],
        voice_color_and_pitch: VoiceColorAndPitchConfig::default(),
        syllabification_config: SyllabificationConfig::default(),
        dictionary_overrides: vec![],
        regex_rules: vec![
            RegexRule::new("gn -> nh", "gn", "nh", 1),
            RegexRule::new("ll -> j", "ll", "j", 2),
            RegexRule::new("x -> h", "x", "h", 3),
            RegexRule::new("seseo z -> s", "z", "s", 4),
        ],
        allow_fallback_cv: true,
        allow_fallback_vv: true,
        split_ratio_onset: 0.5,
        split_ratio_coda: 0.5,
        max_consonant_duration_ms: 120,
        raw_csharp_source: Some(OFFICIAL_SPANISH_SYLLABLE_CS.to_string()),
        source_github_url: Some("https://raw.githubusercontent.com/openutau/OpenUtau/master/OpenUtau.Plugin.Builtin/SpanishSyllableBasedPhonemizer.cs".to_string()),
        custom_usings: vec![
            "using System;".to_string(),
            "using System.Collections.Generic;".to_string(),
            "using System.Linq;".to_string(),
            "using OpenUtau.Api;".to_string(),
            "using OpenUtau.Core.G2p;".to_string(),
        ],
        custom_class_fields: String::new(),
        custom_preprocess_code: String::new(),
        custom_postprocess_code: String::new(),
        custom_helper_methods: String::new(),
            test_cases: Vec::new(),
    }
}
