use crate::models::*;

pub fn create_universal_scratch_preset() -> PhonemizerProject {
    PhonemizerProject {
        name: "MyCustomPhonemizer".to_string(),
        tag: "CUSTOM".to_string(),
        author: "Phonemizer Creator".to_string(),
        version: "1.0.0".to_string(),
        language_code: "mul".to_string(),
        description: "Universal Custom Phonemizer built from scratch".to_string(),
        namespace: "OpenUtau.Plugin.Builtin".to_string(),
        base_class_type: PhonemeSystemType::SyllableBased,
        openutau_plugins_dir: default_openutau_plugins_path(),
        output_dll_name: "MyCustomPhonemizer.dll".to_string(),
        vowels: vec![
            Vowel::new("a"),
            Vowel::new("e"),
            Vowel::new("i"),
            Vowel::new("o"),
            Vowel::new("u"),
        ],
        consonants: vec![
            Consonant::new("k", ConsonantType::Stop),
            Consonant::new("s", ConsonantType::Fricative),
            Consonant::new("t", ConsonantType::Stop),
            Consonant::new("n", ConsonantType::Nasal),
            Consonant::new("m", ConsonantType::Nasal),
            Consonant::new("p", ConsonantType::Stop),
            Consonant::new("l", ConsonantType::Liquid),
            Consonant::new("r", ConsonantType::Liquid),
        ],
        onset_clusters: Vec::new(),
        coda_clusters: Vec::new(),
        pattern_rules: vec![
            PhoneticPatternRule { pattern_type: PatternType::RestingStartVowel, template: "- {vowel}".to_string(), enabled: true, priority: 10, fallback_template: Some("{vowel}".to_string()), min_pitch_note: None, max_pitch_note: None, color_filter: None },
            PhoneticPatternRule { pattern_type: PatternType::RestingStartConsonant, template: "- {consonant}{vowel}".to_string(), enabled: true, priority: 10, fallback_template: Some("{consonant}{vowel}".to_string()), min_pitch_note: None, max_pitch_note: None, color_filter: None },
            PhoneticPatternRule { pattern_type: PatternType::VCV, template: "{prev_vowel} {consonant}{vowel}".to_string(), enabled: true, priority: 9, fallback_template: Some("{consonant}{vowel}".to_string()), min_pitch_note: None, max_pitch_note: None, color_filter: None },
            PhoneticPatternRule { pattern_type: PatternType::CV, template: "{consonant}{vowel}".to_string(), enabled: true, priority: 8, fallback_template: None, min_pitch_note: None, max_pitch_note: None, color_filter: None },
            PhoneticPatternRule { pattern_type: PatternType::EndingVowelGlide, template: "{vowel} -".to_string(), enabled: true, priority: 7, fallback_template: None, min_pitch_note: None, max_pitch_note: None, color_filter: None },
        ],
        voice_color_and_pitch: VoiceColorAndPitchConfig::default(),
        syllabification_config: SyllabificationConfig::default(),
        dictionary_overrides: Vec::new(),
        regex_rules: Vec::new(),
        allow_fallback_cv: true,
        allow_fallback_vv: true,
        split_ratio_onset: 0.5,
        split_ratio_coda: 0.5,
        max_consonant_duration_ms: 120,
        raw_csharp_source: None,
        source_github_url: None,
        custom_usings: vec![
            "using System;".to_string(),
            "using System.Collections.Generic;".to_string(),
            "using System.Linq;".to_string(),
            "using OpenUtau.Api;".to_string(),
            "using OpenUtau.Core.Ustx;".to_string(),
        ],
        custom_class_fields: String::new(),
        custom_preprocess_code: String::new(),
        custom_postprocess_code: String::new(),
        custom_helper_methods: String::new(),
            test_cases: Vec::new(),
    }
}
